### ISSUE TITLE
Thread Sanitizer: DataRace in StreamChat.BaseOperation._finished.setter

### ISSUE THREAD

**Issue by DimDL** [GetStream/stream-chat-swift#2194] opened 2022-07-26 11:50 UTC
## What did you do?
Enable Thread Sanitizer, run app

## What did you expect to happen?
No runtime warnings

## What happened instead?
Runtime warning :
**SUMMARY: ThreadSanitizer: data race AsyncOperation.swift in BaseOperation._finished.setter**

<img width="1392" alt="streamchatBug" src="https://user-images.githubusercontent.com/6987784/180999057-bb7267a3-0daf-468a-a560-8a94624b6d9a.png">

`==================
WARNING: ThreadSanitizer: data race (pid=86526)
  Write of size 1 at 0x00011951adb8 by main thread:
    #0 BaseOperation._finished.setter AsyncOperation.swift (StreamChat:arm64+0x18e98)
    #1 BaseOperation.isFinished.setter AsyncOperation.swift:72 (StreamChat:arm64+0x198ac)
    #2 @objc BaseOperation.isFinished.setter <compiler-generated> (StreamChat:arm64+0x197d4)
    #3 AsyncOperation.handleResult(_:) AsyncOperation.swift:42 (StreamChat:arm64+0x1849c)
    #4 implicit closure #2 in implicit closure #1 in AsyncOperation.start() AsyncOperation.swift:33 (StreamChat:arm64+0x18154)
    #5 partial apply for implicit closure #2 in implicit closure #1 in AsyncOperation.start() <compiler-generated> (StreamChat:arm64+0x1a6fc)
    #6 closure #1 in closure #1 in ExecutePendingOfflineActions.init(offlineRequestsRepository:) SyncOperations.swift:170 (StreamChat:arm64+0x4d92f8)
    #7 partial apply for closure #1 in closure #1 in ExecutePendingOfflineActions.init(offlineRequestsRepository:) <compiler-generated> (StreamChat:arm64+0x4da710)
    #8 closure #5 in OfflineRequestsRepository.runQueuedRequests(completion:) OfflineRequestsRepository.swift:108 (StreamChat:arm64+0x471fb8)
    #9 partial apply for closure #5 in OfflineRequestsRepository.runQueuedRequests(completion:) <compiler-generated> (StreamChat:arm64+0x472054)
    #10 thunk for @escaping @callee_guaranteed () -> () <compiler-generated> (StreamChat:arm64+0x48db8)
    #11 __wrap_dispatch_group_notify_block_invoke <null>:106940280 (libclang_rt.tsan_iossim_dynamic.dylib:arm64+0x79a18)
    #12 _dispatch_client_callout <null>:106940280 (libdispatch.dylib:arm64+0x5b90)
    #13 start_sim <null>:106940280 (dyld_sim:arm64+0x1cd4)

  Previous read of size 1 at 0x00011951adb8 by thread T16:
    #0 BaseOperation._finished.getter AsyncOperation.swift (StreamChat:arm64+0x18db0)
    #1 BaseOperation.isFinished.getter AsyncOperation.swift:68 (StreamChat:arm64+0x1973c)
    #2 @objc BaseOperation.isFinished.getter <compiler-generated> (StreamChat:arm64+0x196b8)
    #3 __NSOQSchedule_f <null>:106940280 (Foundation:arm64+0xef63c)
    #4 _dispatch_client_callout <null>:106940280 (libdispatch.dylib:arm64+0x5b90)

  Location is heap block of size 288 at 0x00011951acc0 allocated by thread T6:
    #0 calloc <null>:106940280 (libclang_rt.tsan_iossim_dynamic.dylib:arm64+0x56748)
    #1 _objc_rootAllocWithZone <null>:106940280 (libobjc.A.dylib:arm64+0x17c7c)
    #2 SyncRepository.syncLocalState(lastSyncAt:completion:) SyncRepository.swift:138 (StreamChat:arm64+0x4dd930)
    #3 closure #1 in SyncRepository.syncLocalState(completion:) SyncRepository.swift:86 (StreamChat:arm64+0x4dc6f0)
    #4 partial apply for closure #1 in SyncRepository.syncLocalState(completion:) <compiler-generated> (StreamChat:arm64+0x4dca90)
    #5 closure #1 in SyncRepository.getUser(completion:) SyncRepository.swift:221 (StreamChat:arm64+0x4e0568)
    #6 partial apply for closure #1 in SyncRepository.getUser(completion:) <compiler-generated> (StreamChat:arm64+0x4e6004)
    #7 thunk for @escaping @callee_guaranteed () -> () <compiler-generated> (StreamChat:arm64+0x48db8)
    #8 developerSubmittedBlockToNSManagedObjectContextPerform <null>:106940280 (CoreData:arm64+0xc1094)
    #9 _dispatch_client_callout <null>:106940280 (libdispatch.dylib:arm64+0x5b90)

  Thread T16 (tid=1675669, running) is a GCD worker thread

  Thread T6 (tid=1675617, running) is a GCD worker thread

SUMMARY: ThreadSanitizer: data race AsyncOperation.swift in BaseOperation._finished.setter
==================
`

## GetStream Environment
**GetStream Chat version:**   - StreamChat (4.18.0), StreamChatUI (4.18.0):
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS 15.5
**Swift version:** 5.6.1
**Xcode version:** 13.4.1
**Device:** iPhone 11 Pro Simulator (Simulator required for Thread Sanitizer)

## Additional context
Attached screenshot

**Comment by polqf** [comment] 2022-07-27 08:02
Hi @DimDL , thank you for the heads up.

I am opening an internal ticket and will tackle it as soon as possible 😄

**Comment by polqf** [comment] 2022-07-27 09:07
Hi again @DimDL. I was not able to reproduce the race condition, but I was able to verify that indeed there were different threads accessing and mutating the state properties of BaseOperation.

I opened a PR, that adds thread safety to it, but would love for you to test it out, if you can, to triple check this issue does not exist anymore: https://github.com/GetStream/stream-chat-swift/pull/2198

Thank you!

**Comment by hugobernalstream** [comment] 2022-08-05 17:53
Hi @DimDL,
The fix that @polqf mentioned is now in our latest release [4.20.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.20.0) Please check again to see if the issue doesn't exists anymore, and let us know.

Thanks!

**Comment by hugobernalstream** [comment] 2022-08-08 17:23
Hi @DimDL,

We are going to close this issue in the mean time that you are able to test and give feedback on the fix.
Feel free to re-open to it with your findings.

Regards,
Hugo

**Closed by hugobernalstream** 2022-08-08 17:23 UTC
Labels: 🐞 Bug
