### ISSUE TITLE
ChannelListVC renders duplicate channels for some time

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swift#1842] opened 2022-03-10 17:52 UTC
I have thread A, B, C, D, E, F. ChannelListVC renders something like A B B, D, E, F .... I tap on the second B and navigate back, I see A B C D E F again.

This was a heisenbug for a while, so I didn't bother to report since I suspect nobody will do anything about it :) but yesterday ... I finally got a consistent repro:

1. Have thread in A, B, C, D, E, F state
2. background the app (and WS becomes disconnected)
3. send a message in thread C
4. foreground the app ==> See thread list becomes C A A D E F!

In ChatChannelListVC channelListController:didChangeChannels callback, these are the changes:
- move 2 => 0
- update 1
- update 3
- update 4
- update 5

When you feed this set of changes into UIVC.performBatchUpdates, UIVC just goes bananas and causes the duplicate rows.

FWIW, when the change set is a single item .move(2, 0), there is no bug.

See the attached video. The view corrects itself because of another "update" change that immediately follows (oh boy, aren't there a TON of update changes coming through all the time). But sometimes there isn't an immediate "update" change that follows, and you'd see the duplicated channels for a while.

https://user-images.githubusercontent.com/97132583/157724417-a456983c-165e-4813-a305-37db0326befc.mp4

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.3
**Swift version:**
**Xcode version:**
**Device:** iPhone 13

**Comment by nuno-vieira** [comment] 2022-03-10 18:04
Hello @linhewinner!

Thank you for the report once again!

Since you are showing the Channel List, by threads, do you mean Channels?

Can you reproduce the bug with offline storage disabled? If no, there is a high change the Offline Support re-built will fix it:  https://github.com/GetStream/stream-chat-swift/pull/1831.

The New Offline Support will most likely be merged next week 👍 

Best,
Nuno

**Comment by linhewinner** [comment] 2022-03-10 18:08
Ah sorry, yes, when I say "thread" I meant "channel". I used to work at Facebook/Messenger, we only talked about "threads" there lol

Let me try local storage

**Comment by linhewinner** [comment] 2022-03-10 18:16
Just turned off localStorage. The bug repros exactly the same way.

I suspect that this is reproducible with a minimalistic UIVC with 6 rows. If you feed .move(2, 0), update(1), update(3), update(4) and update(5), this will probably repro.
And if you attempt to repro, make sure you use iOS 15 since this is probably iOS version dependent.

When I worked with UIVC in the past, I usually take the "updates" out of the changeset, grab the cells and just do a cell.udpateContent call directly. reloadItems causes two problems:
- it causes view flashes because every cell goes through prepareForReuse and is reconfigured (which may include async profile pic setting)
- reloadItems in UIVC.performBatchUpdates cause craziness

**Comment by nuno-vieira** [comment] 2022-03-10 18:29
Hi see, we will then create a ticket internally then to investigate this as soon as we can 👍 

Thank you again,
Nuno

**Comment by nuno-vieira** [comment] 2022-06-02 11:09
Hi @linhewinner!

While I was starting to work on this issue I couldn't reproduce it anymore in the latest release 4.15.0. After checking out the 4.10.0 tag, I could consistently reproduce it, but not with 4.15.0 🙂 

Please update to the latest version when possible to get this issue fixed 👍 

Best Regards,
Nuno

**Closed by nuno-vieira** 2022-06-02 11:09 UTC
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), 📆 Planned
