### ISSUE TITLE
Error Domain=kNWErrorDomainPOSIX Code=53 "Software caused connection abort"

### ISSUE THREAD

**Issue by basememara** [GetStream/stream-chat-swift#1157] opened 2021-06-04 15:01 UTC
## What did you do?

Getting an intermittent failure usually when coming back from background. I am disconnecting when going to background and activating again. The error that occurs completely destroys `URLSession` for the entire app, even libraries and code outside of Stream fail going forward after this error from Stream.

## What did you expect to happen?

No error to occur, especially one that destroys other tasks outside of Stream.

## What happened instead?

Getting this error from Stream:
```
2021-06-04 10:37:18.187251-0400 ***[1222:325127] [websocket] Read completed with an error Software caused connection abort
2021-06-04 10:37:18.195683-0400 ***[1222:324154] Task <FC9798CA-1982-471E-9576-248BC66275AE>.<1> finished with error [53] Error Domain=kNWErrorDomainPOSIX Code=53 "Software caused connection abort" UserInfo={NSDescription=Software caused connection abort, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalWebSocketTask <FC9798CA-1982-471E-9576-248BC66275AE>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalWebSocketTask <FC9798CA-1982-471E-9576-248BC66275AE>.<1>}
2021-06-04 10:37:18.193 [ERROR] [io.getStream.chat.core.web_socket_engine_queue] [URLSessionWebSocketEngine.swift:62] [doRead()] > Failed receiving Web Socket Message with error: Error Domain=kNWErrorDomainPOSIX Code=53 "Software caused connection abort" UserInfo={NSDescription=Software caused connection abort}
```

Other tasks outside of Stream die as well with an error like this:
```
2021-06-04 10:37:28.784494-0400 ***[1222:325139] Task <B112EBE2-4601-454D-B921-9E931D0B63A9>.<215> finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x28271d5c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <B112EBE2-4601-454D-B921-9E931D0B63A9>.<215>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <B112EBE2-4601-454D-B921-9E931D0B63A9>.<215>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://http-intake.logs.datadoghq.com/v..., NSErrorFailingURLKey=https://http-intake.logs.datadoghq.com/v..., _kCFStreamErrorDomainKey=4}
```

## GetStream Environment
**GetStream Chat version:** `main` branch, commit `1e87f5db534df7e43c5982844aaa2b07450ca805`, but noticed it in earlier version back to `4.0-beta.1`
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS 14.5
**Swift version:** Swift 5.4
**Xcode version:** Xcode 12.5
**Device:** iPhone X physical device and also simulator

**Comment by b-onc** [comment] 2021-06-04 15:03
Hello @basememara ,

This is an interesting issue, thanks for the description. You mentioned you're handling the connect/disconnect flow yourself. Can you describe your architecture/code, or steps to reproduce for this issue? A sample project would highly be preferred, since this sounds very tricky.

**Comment by basememara** [comment] 2021-06-06 01:04
The original app is large and quite complex, I've done my best to extract the relevant parts while retaining the essence of the application architecture. I placed it into a working sample repo here: https://github.com/basememara/GetStreamSwiftUISample

The connect logic does the following steps in a `Combine` chain within a `ChatService` wrapper:

1. Set the token and user
2. Connect to Stream service
3. Construct a queried channel list controller
4. Synchronize the channels
5. Publish changes to view model going forward

```swift
extension ChatServiceStream {
    func connect(userToken: String) {
        cancellable.removeAll()
        subscribe()

        do {
            chatClient.tokenProvider = .static(try Token(rawValue: userToken))
            debugPrint("The chat token was successfully assigned")
        } catch {
            debugPrint("An error occured while configuring the chat client")
            return
        }

        chatClient.currentUserController().reloadUserIfNeeded { [weak self] error in
            error == nil
                ? debugPrint("The chat user '\(self?.userID ?? "unknown")' was successfully reloaded")
                : debugPrint("An error occured while reloading the chat client: \(String(describing: error))")
        }

        chatClient.connectionController().connect { [weak self] error in
            error == nil
                ? debugPrint("The chat user '\(self?.userID ?? "unknown")' was successfully connected")
                : debugPrint("An error occured while connecting the chat client: \(String(describing: error))")
        }
    }
}

private extension ChatServiceStream {
    func subscribe() {
        chatClient.connectionController()
            .connectionStatusPublisher
            .handleEvents(receiveOutput: { status in debugPrint("Chat connection status: \(status)") })
            .filter { $0 == .connected }
            .compactMap { [weak self] _ in self?.currentUser }
            .handleEvents(receiveOutput: { debugPrint("Chat user '\($0.id)' was successfully connected") })
            .filter { $0.userRole != .anonymous }
            .compactMap { [weak self] (currentUser) -> ChatChannelListController? in
                guard let self = self else { return nil }

                self.chatChannelListController = self.chatClient.channelListController(
                    query: ChannelListQuery(
                        filter: .and(
                            [
                                .equal(.type, to: self.channelType),
                                .or([
                                    .containMembers(userIds: [currentUser.id]),
                                    .equal("isRecommended", to: true)
                                ])
                            ]
                        )
                    )
                )

                debugPrint("Created chat channel list controller instance")
                return self.chatChannelListController
            }
            .flatMap(maxPublishers: .max(1)) { controller in
                Publishers.Merge(
                    Future { promise in
                        controller.synchronize { error in
                            guard error == nil else {
                                debugPrint("An error occured while fetching the chat channel list: \(String(describing: error))")
                                return
                            }

                            debugPrint("Synchronized chat channel list controller")
                            promise(.success(()))
                        }
                    },
                    controller.channelsChangesPublisher
                        .handleEvents(receiveOutput: { changes in debugPrint("Chat channels list changes: \(changes.count)") })
                        .map { _ in }
                )
            }
            .filter { [weak self] _ in self?.currentUser?.userRole != .anonymous }
            .compactMap { [weak self] _ in self?.chatChannelListController?.channels.map(ChannelViewModel.init) }
            .sink { Self.channelSubject.send($0) }
            .store(in: &cancellable)
    }
}
```

In the `ContentView`, the chat service connects and disconnects on `.active` and `.background` phases:

```swift
struct ContentView: View {
    let chatService: ChatService
    let userToken: String

    var body: some View {
        ...
    }
    .onChange(of: phase) {
        switch newPhase {
        case .active:
            chatService.connect(userToken: userToken)
        case .background:
            chatService.disconnect()
        default:
            break
        }
    }
```

This is the output to the console:

```
"Chat connection status: initialized"
"The chat token was successfully assigned"
"The chat user \'*****\' was successfully reloaded"
"Chat connection status: connecting"
"The chat user \'*****\' was successfully connected"
"Chat connection status: connecting"
"Chat connection status: connected"
"Chat user \'*****\' was successfully connected"
"Created chat channel list controller instance"
"Chat channels list changes: 20"
"Synchronized chat channel list controller"
"Chat channels list changes: 19"
```

It is an intermittent issue so it's hard to reproduce. I might be doing something wrong so I'd appreciate any insight and guidance.

**Comment by b-onc** [comment] 2021-08-13 11:53
Hello @basememara ,

We've updated our SDK to be more robust during Websocket connection. This issue shouldn't happen anymore. Can you test and let me know?

**Comment by hovmush** [comment] 2021-08-15 22:04
Hello. I have the same issue. It's happening when I'm connecting and disconnecting a lot of times. 
SDK - StreamChat (4.0.0-beta.11)

**Comment by tbarbugli** [comment] 2021-09-20 14:49
@basememara @hovmush latest release (4.0.1) improved connection handling, can you reproduce this on that version as well?

**Comment by hovmush** [comment] 2021-09-22 06:26
Thank you @tbarbugli. I will try and let you know

**Comment by tbarbugli** [comment] 2021-09-27 09:32
@hovmush I will close this for now, please re-open if you still see the problem

**Closed by tbarbugli** 2021-09-27 09:32 UTC
Labels: bug
