### ISSUE TITLE
Adding a threaded reply increments the wrong message's reply count

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1389] opened 2021-08-19 16:04 UTC
## What did you do?
Added a threaded reply to a message.

## What did you expect to happen?
That message's thread reply count to be incremented

## What happened instead?
A different message's thread reply count was incremented

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.10
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
See attached sample project
[StreamTest.zip](https://github.com/GetStream/stream-chat-swift/files/7015923/StreamTest.zip)
Steps to reproduce:
- Start app, select "Enter .support Chat Channel"
- Long press on the oldest chat message that says "Really?" (it comes after the messages "3" through "13") and select to add a threaded reply
- Add a threaded reply
- Navigate out of the threaded reply screen
- Notice the number of thread replies for the "10" message is incorrectly incremented

**Comment by dmigach** [comment] 2021-08-20 09:07
Hello @srgray ! Thanks for reporting this, I'm going to check out the issue in your sample project

**Comment by dmigach** [comment] 2021-08-20 15:39
What I think created confusion here is the following:
"Really?" is actually a message that was sent to the "10" message's thread with a checkmark "also send in channel" active.
So the fact that when you add more replies to it, it increments the number of replies for "10" is correct. 
Although I noticed that at the moment the number is 11, but there are actually just 6 replies presented.
I was testing this in your project to figure out the root cause when the token expired, do you think it would be possible for you to generate another expiring one?

**Comment by srgray** [comment] 2021-08-20 16:22
@dmigach Ah, that makes, thanks for the explanation.

Yes, here is another token:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZDZhZjY2NmUtNmVmYS00ZDAwLWE1NWMtZjEyYTFhODNlZjIyIiwiZXhwIjoxNjI5NTU4MjM5fQ.MIWTs9fbcVkdx1uWhCy22Dgbi-FI3D13xikyiIQsaSo`

**Comment by dmigach** [comment] 2021-08-23 13:04
Aaand it's expired again 😅 Can you generate one that would be fresh for several days using this page https://getstream.io/chat/docs/react/token_generator/ ?

**Comment by srgray** [comment] 2021-08-23 13:09
Ah, yes, thanks for that link, I didn't realize that existed.

Here is a fresh token:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMGRiZDcyOGItNDE3NS00MmUzLWI0NGItY2QyMGFiODVkZmM1IiwiZXhwIjoxNjMwMTU2MDYxfQ.XheRl3w2i4zqUllRH_PuxSc659nVw1XFi6hXt8csiL4`

**Comment by dmigach** [comment] 2021-08-31 15:06
Hi @srgray !
We were able to spot the issue, we're going to merge a fix and after that I'll let you know which version is going to include it

**Comment by tbarbugli** [comment] 2021-09-06 07:38
The solution for this is released in the 4.0-rc1 release. Please reopen if you still experience this problem

**Closed by tbarbugli** 2021-09-06 07:38 UTC
Labels: bug
