### ISSUE TITLE
ChatClient.currentUserController().addDevice not working

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1041] opened 2021-04-30 18:16 UTC
## What did you do?
Call addDevice after connecting to Stream like this:
```
ChatClient.shared.connectionController().connect { error in
            ChatClient.shared.currentUserController().addDevice(token: deviceToken) { error in
               if let error = error {
                   DDLogError("Failed to register deviceToken with Stream: \(error.legibleDescription)")
               } else {
                   DDLogInfo("Successfully registered deviceToken with Stream")
               }
           }
}
```
## What did you expect to happen?
The device to be successfully registered

## What happened instead?
addDevice failed with error:
```
Error CurrentUserDoesNotExist in /Users/........./Pods/StreamChat/Sources/StreamChat/Controllers/CurrentUserController/CurrentUserController.swift:220 -> There is no `CurrentUserDTO` instance in the DB. Make sure to call `Client.setUser`.
```

## GetStream Environment
**GetStream Chat version:**
3.2.0-beta.8
**GetStream Chat frameworks:** StreamChat

**Comment by b-onc** [comment] 2021-05-12 12:05
Hello @srgray 
I cannot reproduce the issues with latest beta, the same code you've provided works for me. Can you share how you're creating the client - or better - an example project?
Also, you don't need to manually call `connect` if you're using the default `ChatClientConfig`

**Comment by srgray** [comment] 2021-05-12 12:52
OK, I upgraded to latest 3.2.0-beta.10 and am still seeing this error. Here is how I create the client:

```
extension ChatClient {
    /// The singleton instance of `ChatClient`
    static let shared: ChatClient = {
        var config = ChatClientConfig(apiKeyString: Configuration.streamAPIKey)
        config.shouldConnectAutomatically = true
        config.baseURL = .usEast
        config.isLocalStorageEnabled = false
        return ChatClient(config: config, tokenProvider: .anonymous)
    }()
}
```
I switched back to automatic connection, as you suggested. I am using `.anonymous` token because my user is not logged in yet. After user login, I do this to setup the user token and device registration:

```
        ChatClient.shared.tokenProvider = .closure { chatClient, completion in
            // get token from my api backend and call completion
        }
        ChatClient.shared.currentUserController().reloadUserIfNeeded { error in
            if let error = error {
                DDLogError(error.legibleDescription)
            } else {
                ChatClient.shared.currentUserController().addDevice(token: deviceToken) { error in
                    if let error = error {
                        DDLogError("Failed to register deviceToken with Stream: \(error.legibleDescription)")
                    } else {
                        DDLogInfo("Successfully registered deviceToken with Stream")
                    }
                }
            }
        }
```

If this is not enough info, I can try to extract this into a sample project.

**Comment by basememara** [comment] 2021-05-29 06:54
Did you figure this out? I'm initially using `.anonymous` until the user session is initialized then try to change the token provide but the `reloadUserIfNeeded` is not updating it.

**Comment by b-onc** [comment] 2021-06-07 12:53
Hello @srgray and @basememara 
This issue was resolved in 4.0.0-beta.2. Are you still getting `CurrentUserDoesNotExist` error even when you wait for the completion of `reloadUserIfNeeded`?

**Comment by srgray** [comment] 2021-06-07 16:28
@b-onc After upgrading to 4.0.0-beta.2, I do not see any error from the `addDevice` call.

I have not been able to successfully receive a push notification on that device, though. I see these errors in the Stream Dashboard push logs:
```publishing the message failed. code = "400"; error = "BadDeviceToken"; device is disabled```

Let me know if I should create a new issue to track that error.

**Comment by kcollignon** [comment] 2021-06-08 06:09
+1 we are getting the same message, `publishing the message failed. code = "400"; error = "BadDeviceToken"; device is disabled`

**Comment by b-onc** [comment] 2021-06-14 12:58
Hello @srgray @kcollignon 
That error usually means your APN Config is not valid. Please check our docs here: https://getstream.io/chat/docs/ios-swift/ios_push_notifications/?language=swift#testing-if-push-notifications-are-setup-correctly

**Closed** 2021-06-14 12:59 UTC
Labels: question, sdk:StreamChat
