### ISSUE TITLE
Failed to decode event from event payload

### ISSUE THREAD

**Issue by zeeshansuleman** [GetStream/stream-chat-swift#2302] opened 2022-09-15 14:28 UTC
## What did you do?
@martinmitrevski I created the channel and channel created successfully and then navigate ti the Stream ChatChannelView. Sometimes chat show but sometime loader show for infinite time. 

```Swift
ChatChannelView(
    viewFactory: CustomChatViewFactory.shared,
    channelController: controller
)
```

See the following video, loader show for infinite time.  

https://user-images.githubusercontent.com/12757747/190428150-f3b674d5-81d0-4e82-9dbf-786606fb9ee1.mov

Also your can see the error logs 
```
2022-09-15 09:08:31.130 [ERROR] [com.apple.NSURLSession-delegate] [EventPayload.swift:176] [asEvents()] > Failed to decode event from event payload: 
-----EventPayload-----
     eventType: EventType(rawValue: "channel.created")
     connectionId: nil
     cid: Optional(messaging:!members-AXdIGUxchCL5atGvfTJaVfSsZFgKpPjyndR1mNqYEOg)
     currentUser: nil
     user: Optional(StreamChat.UserPayload)
     createdBy: nil
     memberContainer: nil
     channel: Optional(StreamChat.ChannelDetailPayload(cid: messaging:!members-AXdIGUxchCL5atGvfTJaVfSsZFgKpPjyndR1mNqYEOg, name: Optional("skillr1007"), imageURL: nil, extraData: ["own_capabilities": StreamChat.RawJSON.array([StreamChat.RawJSON.string("connect-events"), StreamChat.RawJSON.string("create-call"), StreamChat.RawJSON.string("delete-channel"), StreamChat.RawJSON.string("delete-own-message"), StreamChat.RawJSON.string("flag-message"), StreamChat.RawJSON.string("join-call"), StreamChat.RawJSON.string("join-channel"), StreamChat.RawJSON.string("leave-channel"), StreamChat.RawJSON.string("mute-channel"), StreamChat.RawJSON.string("pin-message"), StreamChat.RawJSON.string("quote-message"), StreamChat.RawJSON.string("read-events"), StreamChat.RawJSON.string("search-messages"), StreamChat.RawJSON.string("send-custom-events"), StreamChat.RawJSON.string("send-links"), StreamChat.RawJSON.string("send-message"), StreamChat.RawJSON.string("send-reaction"), StreamChat.RawJSON.string("send-reply"), StreamChat.RawJSON.string("send-typing-events"), StreamChat.RawJSON.string("typing-events"), StreamChat.RawJSON.string("update-channel"), StreamChat.RawJSON.string("update-own-message"), StreamChat.RawJSON.string("upload-file")]), "disabled": StreamChat.RawJSON.bool(false)], typeRawValue: "messaging", lastMessageAt: nil, createdAt: 2022-09-15 14:08:21 +0000, deletedAt: nil, updatedAt: 2022-09-15 14:08:21 +0000, truncatedAt: nil, createdBy: Optional(StreamChat.UserPayload), config: StreamChat.ChannelConfig, isFrozen: false, isHidden: nil, members: Optional([StreamChat.MemberPayload(user: StreamChat.UserPayload, role: Optional(StreamChat.MemberRole(rawValue: "member")), createdAt: 2022-09-15 14:08:21 +0000, updatedAt: 2022-09-15 14:08:21 +0000, banExpiresAt: nil, isBanned: Optional(false), isShadowBanned: Optional(false), isInvited: nil, inviteAcceptedAt: nil, inviteRejectedAt: nil), StreamChat.MemberPayload(user: StreamChat.UserPayload, role: Optional(StreamChat.MemberRole(rawValue: "member")), createdAt: 2022-09-15 14:08:21 +0000, updatedAt: 2022-09-15 14:08:21 +0000, banExpiresAt: nil, isBanned: Optional(false), isShadowBanned: Optional(false), isInvited: nil, inviteAcceptedAt: nil, inviteRejectedAt: nil)]), memberCount: 2, invitedMembers: [], team: nil, cooldownDuration: 0))
     message: nil
     reaction: nil
     watcherCount: nil
     unreadCount: nil
     createdAt: Optional(2022-09-15 14:08:21 +0000)
     isChannelHistoryCleared: nil
     banReason: nil
     banExpiredAt: nil
     parentId: nil
     hardDelete: false
, error: Error UnknownChannelEvent in /Users/mac/Library/Developer/Xcode/DerivedData/Skillr-cuwdfsgkghswrggqlelxfpxovrrb/SourcePackages/checkouts/stream-chat-swift/Sources/StreamChat/WebSocketClient/Events/EventType.swift:173 -> Event with EventType(rawValue: "channel.created") cannot be decoded as system event.
```
<img width="993" alt="Screenshot 2022-09-15 at 9 21 52 AM" src="https://user-images.githubusercontent.com/12757747/190429895-1e0293bb-b25c-43e8-81e1-f38dc4f1a79b.png">
<img width="996" alt="Screenshot 2022-09-15 at 9 22 02 AM" src="https://user-images.githubusercontent.com/12757747/190429913-295cfe7b-0bbd-4ce5-8037-1d076084f3cd.png">

## What did you expect to happen?
When channel created successfully then ChatChannelView should show the chat like following screenshot instead of the loader for infinite time.

<img width="326" alt="Screenshot 2022-09-15 at 9 23 31 AM" src="https://user-images.githubusercontent.com/12757747/190429292-603a8dcd-67d1-45b0-a0d4-47e6dc8ec150.png">

## What happened instead?
ChatChannelView just show the loader instead of chat due the mentioned error. 

<img width="329" alt="Screenshot 2022-09-15 at 9 28 31 AM" src="https://user-images.githubusercontent.com/12757747/190430463-60481d7d-85f3-4d35-80cb-71094561b8d8.png">

## GetStream Environment
**GetStream Chat version:**
4.20.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
4.20.0
**iOS version:**
15
**Swift version:**
Swift 5
**Xcode version:**
13.4.1
**Device:**
IPhone 11, IPhone 11 Pro, IPhone 6s

**Comment by polqf** [comment] 2022-09-22 14:02
Hi @zeeshansuleman ,
I was investigating this issue, and the error log is a false positive, but there is no issue around that.
The error will disappear when this PR https://github.com/GetStream/stream-chat-swift/pull/2314 is merged.

We need to understand what is causing you this never-ending spinner, but this is not the root cause of the problem.

Please try out the branch of the PR and let us know if there is any other thing that you could spot. Otherwise please inspect the network traffic and let us know if any request is failing for you. It was impossible for us to reproduce the issue

**Comment by polqf** [comment] 2022-09-26 10:43
Hi @zeeshansuleman ,

There is an error in your code, you are calling `onComplete` synchronously without waiting for the response from `synchronize`
```
        channelController?.synchronize { error in
            if let error = error {
                logger.error("There is an error in creating channel: \(error)", category: .chat)
                onComplete("Channel creation failed with error: \(error.localizedDescription)")
                return
            }
            self.selectedChannel = self.channelController?.channel
            // <--------- You should call `onComplete(nil)` here.
        }
        onComplete(nil) // <-------- This is wrong
```

**Closed by polqf** 2022-09-26 10:43 UTC

**Comment by zeeshansuleman** [comment] 2022-09-26 11:10
@polqf Issue is still exists.

Now, I am using the `onComplete` inside.

```swift
channelController?.synchronize { error in
            if let error = error {
                logger.error("There is an error in creating channel: \(error)", category: .chat)
                onComplete("Channel creation failed with error: \(error.localizedDescription)")
                return
            }
            self.selectedChannel = self.channelController?.channel
            onComplete(nil)
        }
```

First, I started chat with other 4 to 5 users by creating the channel and when I create channel to chat with 6th user, I am getting the same error while synchronizing the channelController. We are getting this error randomly by creating the channel. 

```
-----EventPayload-----
     eventType: EventType(rawValue: "channel.created")
     connectionId: nil
     cid: Optional(messaging:!members-Rcy-Yq-teckuy9kYlAd6lc54rZ9pu7wJ17EHpzhc4lA)
     currentUser: nil
     user: Optional(StreamChat.UserPayload)
     createdBy: nil
     memberContainer: nil
     channel: Optional(StreamChat.ChannelDetailPayload(cid: messaging:!members-Rcy-Yq-teckuy9kYlAd6lc54rZ9pu7wJ17EHpzhc4lA, name: Optional("NestorF"), imageURL: nil, extraData: ["disabled": StreamChat.RawJSON.bool(false), "own_capabilities": StreamChat.RawJSON.array([StreamChat.RawJSON.string("connect-events"), StreamChat.RawJSON.string("create-call"), StreamChat.RawJSON.string("delete-channel"), StreamChat.RawJSON.string("delete-own-message"), StreamChat.RawJSON.string("flag-message"), StreamChat.RawJSON.string("join-call"), StreamChat.RawJSON.string("join-channel"), StreamChat.RawJSON.string("leave-channel"), StreamChat.RawJSON.string("mute-channel"), StreamChat.RawJSON.string("pin-message"), StreamChat.RawJSON.string("quote-message"), StreamChat.RawJSON.string("read-events"), StreamChat.RawJSON.string("search-messages"), StreamChat.RawJSON.string("send-custom-events"), StreamChat.RawJSON.string("send-links"), StreamChat.RawJSON.string("send-message"), StreamChat.RawJSON.string("send-reaction"), StreamChat.RawJSON.string("send-reply"), StreamChat.RawJSON.string("send-typing-events"), StreamChat.RawJSON.string("typing-events"), StreamChat.RawJSON.string("update-channel"), StreamChat.RawJSON.string("update-own-message"), StreamChat.RawJSON.string("upload-file")])], typeRawValue: "messaging", lastMessageAt: nil, createdAt: 2022-09-26 10:49:53 +0000, deletedAt: nil, updatedAt: 2022-09-26 10:49:53 +0000, truncatedAt: nil, createdBy: Optional(StreamChat.UserPayload), config: StreamChat.ChannelConfig, isFrozen: false, isHidden: nil, members: Optional([StreamChat.MemberPayload(user: StreamChat.UserPayload, role: Optional(StreamChat.MemberRole(rawValue: "member")), createdAt: 2022-09-26 10:49:53 +0000, updatedAt: 2022-09-26 10:49:53 +0000, banExpiresAt: nil, isBanned: Optional(false), isShadowBanned: Optional(false), isInvited: nil, inviteAcceptedAt: nil, inviteRejectedAt: nil), StreamChat.MemberPayload(user: StreamChat.UserPayload, role: Optional(StreamChat.MemberRole(rawValue: "member")), createdAt: 2022-09-26 10:49:53 +0000, updatedAt: 2022-09-26 10:49:53 +0000, banExpiresAt: nil, isBanned: Optional(false), isShadowBanned: Optional(false), isInvited: nil, inviteAcceptedAt: nil, inviteRejectedAt: nil)]), memberCount: 2, invitedMembers: [], team: nil, cooldownDuration: 0))
     message: nil
     reaction: nil
     watcherCount: nil
     unreadCount: nil
     createdAt: Optional(2022-09-26 10:49:53 +0000)
     isChannelHistoryCleared: nil
     banReason: nil
     banExpiredAt: nil
     parentId: nil
     hardDelete: false
, error: Error UnknownChannelEvent in /Users/mac/Library/Developer/Xcode/DerivedData/Skillr-egjtvijyzdchlaffvmbsutsfboie/SourcePackages/checkouts/stream-chat-swift/Sources/StreamChat/WebSocketClient/Events/EventType.swift:173 -> Event with EventType(rawValue: "channel.created") cannot be decoded as system event.
2022-09-26 05:52:25.644 [ERROR] [com.apple.NSURLSession-delegate] [EventPayload.swift:176] [asEvents()] > Failed to decode event from event payload: 
```

- We got the above error 5 yo 7 times again and again on creating that channel. 
- What would be the possible solution for that?

**Comment by polqf** [comment] 2022-09-26 11:14
As I told you in a previous message, `UnknownChannelEvent` is NOT an issue, but a false positive. It was solved in https://github.com/GetStream/stream-chat-swift/pull/2314, and you can test it by using `develop` branch.
