### ISSUE TITLE
Messages sometimes missing from chat

### ISSUE THREAD

**Issue by alexandersandberg** [GetStream/stream-chat-swift#2423] opened 2022-12-20 15:46 UTC
## What did you do?

After upgrading past 4.22.0, we started noticing that the chat was sometimes not displaying all messages in the chat history. According to the logs, the messages are there, but some are not displayed.

## What did you expect to happen?

All chat messages are always displayed.

## What happened instead?

When first opening the chat, some messages are not displayed. If the chat is closed and opened again, all messages are there.

## GetStream Environment
**GetStream Chat version:** 4.25.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.0
**Swift version:** 5.7
**Xcode version:** 14.0
**Device:** iPhone 14 Pro

## Additional context

We thought it could be something on our side, but by simply downgrading to 4.21.2 the issues disappeared, and I didn't notice anything in the changelog that needed to be addressed.

I have not seen any error messages in the logs.

Sadly, that's all the information I have for now.

**Comment by Crysis21** [comment] 2022-12-20 18:20
there is a similar issue with reactions and replies. something is wrong with core data storage.

**Comment by nuno-vieira** [comment] 2022-12-20 22:34
Hi @alexandersandberg, @Crysis21,

Can you please provide more details?

> According to the logs
Which logs? Can you share these logs?

Can you provide reproducible steps? 
Is this reproducible in the DemoApp?
Do you have customizable components? If you remove the customization, is it still reproducible?

Best,
Nuno

**Comment by alexandersandberg** [comment] 2022-12-22 10:10
I will get back to you with these details as soon as possible, but it might take some time due to the holidays—sorry about that!

**Comment by rlindsey2** [comment] 2022-12-22 23:56
@nuno-vieira A couple of our users have also reached out to us about this and we are on version 4.22.0, so a slightly earlier version than Alex reported. This is a big issue for us since chat is a core functionality of our app.

GetStream Chat version: 4.22.0
GetStream Chat frameworks: StreamChat, StreamChatUI
iOS version: 16.0
Swift version: 5.7
Xcode version: 14.0
Device: Reproduced on iPhone 11, 14 Pro 

We tried to reproduce this a few times and found we could do so by:
1. Put both devices in 'Very bad Network' mode
2. On the receiving users device, leave the chat view
3. Send ordered number of messages. We went up to 19.
4. Receiving user taps on the message notification numbered 11.
5. Receiving users stays in the chat until receiving the last message numbered 19. We noticed a few messages were missing. 10,11,12, and 13. So one before the tapped notification, 2 after.
6. Go back out of chat and back in and all the messages show in the correct order from 1 through to 19.

This didn't reproduce the issue every time but I'd say 20% of the time we could using the above steps.

One thing to note, is we do not use the ChatChannelListView. We push the ChatChannelView from our own custom view. The only custom UI we use is by changing the ChatChannelHeaderViewModifier, so all the chat UI is using your SwiftUI library. Please let me know if you want anything else. 
![IMG_5406](https://user-images.githubusercontent.com/37937966/209244736-e03ecadb-c316-4adc-897d-144a2c6af479.PNG)

**Comment by nuno-vieira** [comment] 2022-12-23 11:55
Hi @rlindsey2,

Thank you for the additional details. But if the network is in a very bad condition, this can be normal behaviour, some messages might fail to be delivered and others not. But we will try to reproduce this on our end and see if it is an actual issue. 

Best,
Nuno

**Comment by rlindsey2** [comment] 2022-12-27 00:42
This was just one way that we were able to reproduce it however the fact that users are commonly coming into this issue and churning from our product due to not a good enough chat experience shows that this is likely happening in other states are should be handled better. Also given the fact 3 different users of your service has brought this up in a week seems to indicate if could be fairly common.
The notifications for all of the messages were coming through so they had been received through the fcm network. I'd imagine you need to have some guarantee of message ordering when you display them in the feed. i.e. if you're missing a message do not show any following ones until you know you're up-to-date. That seems to create the most confusion.

**Comment by alexandersandberg** [comment] 2022-12-27 06:25
Thanks, @rlindsey2 for providing more details!

@nuno-vieira While I'm still out for the holidays and not able to add much more details myself at the moment, I can say with 99% certainty that this is not due to a bad internet connection.

**Comment by nuno-vieira** [comment] 2022-12-27 17:54
Hi @rlindsey2, @alexandersandberg,

I'm not saying the issue is not real. What I was saying is that in that particular testing scenario it could be just related to networking conditions only.

We are also on holiday this week, but once we come back we will resume the investigation. 

Best,
Nuno

**Comment by AndrewSB** [comment] 2023-01-04 01:10
hey @nuno-vieira we're experiencing this too

we were on 4.22 though, i've just updated to 4.25 to see if it's any better. 

based on @alexandersandberg's experience though, i'm pretty sure the problem will still be there

**Comment by nuno-vieira** [comment] 2023-01-04 11:23
Hi @AndrewSB,

Do you have reproducible steps? We still can't seem to reproduce this, at least in our DemoApp. 

Best,
Nuno

**Comment by nuno-vieira** [comment] 2023-01-04 12:02
Hi @AndrewSB, @Crysis21, @alexandersandberg!

I was actually able to reproduce this more consistently. Do you guys have a custom value of `messagesLimit` in the Channel List Query? (For the ones which are using a channel list)

By setting this value to 1 for example, and following the steps [here](https://github.com/GetStream/stream-chat-swift/issues/2423#issuecomment-1363447181), even without worrying about network connection, I'm able to reproduce this almost 100%. So this will help us pinpoint the problem most likely. But just want to make sure that the issue is related only to changing this value or opening a channel without a channel list. 

Best,
Nuno

**Comment by alexandersandberg** [comment] 2023-01-04 12:10
Hey @nuno-vieira, great to hear!

We are indeed using a custom `messagesLimit`, which is set to `1`.

**Comment by nuno-vieira** [comment] 2023-01-04 16:40
> Hey @nuno-vieira, great to hear!
> 
> We are indeed using a custom `messagesLimit`, which is set to `1`.

Exactly... This way now I can reproduce it quite often :) We will now be able to provide a fix soon. We will let you know once we have it fixed. 

Best,
Nuno

**Comment by AndrewSB** [comment] 2023-01-10 23:16
this is expected to land in the next release after 4.25.1? does the team have a target for when that will be released?

**Comment by nuno-vieira** [comment] 2023-01-10 23:49
@AndrewSB Yes, it will be available on 4.26.0. The ETA for the release is later this week or early next week. But we will keep you posted 👍

**Comment by nuno-vieira** [comment] 2023-01-13 16:29
Hi guys, this fix is now available in the 4.26.0 release.

Best,
Nuno

**Closed by nuno-vieira** 2023-01-13 16:29 UTC
Labels: 🐞 Bug, ❗️ High Priority, 🌐 SDK: StreamChat (LLC), 🔜 Upcoming
