### ISSUE TITLE
Threaded Giphy message not show after reply it in thread

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2303] opened 2022-08-05 14:02 UTC
## What did you do?
- send a Giphy in thread chat with check the “Also send in channel”
- reply the Giphy has just sent in thread chat with check the “Also send in channel”
- Back to chat screen
- Actual GIPHY message disappeared

## What did you expect to happen?
- The GIPHY message should be visible

## What happened instead?
- The Giphy I sent before has been disappeared

## GetStream Environment
**GetStream Chat version:** 4.20.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-x

## Additional context

https://user-images.githubusercontent.com/47667077/183092320-563d2cb4-f1bf-4ad3-b685-b75df34a71ba.mp4

**Comment by polqf** [comment] 2022-09-23 09:54
Hi @ajay-simform , I have been trying to reproduce the issue in both SwiftUI and UIKit SDKs, but I was unable.
I even went back to 4.20.0 on the SwiftUI Demo and could not reproduce it 🤔 

Uploading Simulator Screen Recording - iPhone 13 Pro - 2022-09-23 at 13.52.48.mp4…

**Comment by polqf** [comment] 2022-09-23 12:25
Closing it for now as it seems unreproducible. Might have been a temporary issue in our Backend

**Closed by polqf** 2022-09-23 12:25 UTC
