### ISSUE TITLE
Weird order of images and text

### ISSUE THREAD

**Issue by jrBordet** [GetStream/stream-chat-swift#2203] opened 2022-08-02 08:29 UTC
## What did you do?
Sharing images and text on the chat

Steps to reproduce: 

1. Enter the chat and share some image with some text and exit the chat
2. Send any text and exit the chat
6. Enter into the chat and notice that the text inserted in previous steps is changing the places as if the ones sent first are disappearing

## What did you expect to happen?
The order of the messages and the images should never change

## What happened instead?
Sometimes the order of the messages and the images changes

```
io.getStream.chat.core.web_socket_engine_queue] [URLSessionWebSocketEngine.swift:62] [doRead()] > Failed receiving Web Socket Message with error: Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected"
```

## GetStream Environment
**GetStream Chat version: 4.18.0**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by hugobernalstream** [comment] 2022-08-02 17:21
Hi @jrBordet, 

Thank you for your report! It could help us to have more detailed info so we can narrow it down better, so could you provide:

- What SKD version are you currently using?
- Do you have any customization on the message list or around the ChatClient?
- Can you reproduce this issue in our DemoApp?

Any additional context that you could provide to us that can help us determine the issue is appreciated.

**Comment by hugobernalstream** [comment] 2022-08-12 19:57
Hi,

Closing this issue for now. Feel free to reopen it if you have more information or questions on the matter.

Regards,
Hugo

**Closed by hugobernalstream** 2022-08-12 19:57 UTC
