### ISSUE TITLE
Offline mode resets channels list

### ISSUE THREAD

**Issue by pelczark** [GetStream/stream-chat-swift#2021] opened 2022-05-24 10:05 UTC
## What did you do?
In my app user has over 100 channels with a single user. I'm using the default UI from StreamChatUI.
Channels list is paginated. I scroll down to the bottom to see f.e. 80th channel.
I encountered two issues:
1. When the internet connection is lost and then is reconnected again, then I try to load more pages, the channel list scrolls up, and I see only the first channels page (20 channels).
~~2. When I open the 80th channel details screen, turn on and off flight mode, and try to send a new message the red indicator shows up. I long press the message and press "Try again" without success.~~

## What did you expect to happen?
1. The channels list shouldn't scroll up and user should be able to see the 80th channel.
~~2. User should be able to send a message when connection is regained.~~

## What happened instead?
1. Channels list scrolls up, only first 20 channels are visible.
~~2. The message cannot be sent.~~

## GetStream Environment
**GetStream Chat version:** 4.15.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.4.1
**Swift version:** 5
**Xcode version:** 13.3.1
**Device:** iPhone 11 Pro

**Comment by polqf** [comment] 2022-05-25 07:42
HI @pelczark,

Thank you for opening this ticket.

The first issue is known, and it is currently not a priority. We'll let you know when this changes.

The second one is unknown, and should not happen. Let me come back to you after I investigate it. Is there any particular thing you are doing to reproduce it?

**Comment by hugobernalstream** [comment] 2022-05-27 15:18
Hi @pelczark,

After a first investigation of 2. with the details you provided, I wasn't able to reproduce the issue you mention. I was able to properly resend the message after turning airplane mode off, regaining connection and long-pressing the failed message to resend it.

Is it possible for you to send a video reproducing the issue? 
Have you tried to reproduce the issue in our DemoApp?
Is there any customization you are adding around ChatChannel?

**Comment by pelczark** [comment] 2022-05-30 07:45
Hi. I retested `2` using the newest library and it is working. Apologies, It didn't work in the older version.

**Comment by polqf** [comment] 2022-05-30 08:39
That's great to hear! We'll keep you posted on `1` as it is not in our roadmap now

**Comment by nuno-vieira** [comment] 2022-12-16 20:41
Closing this issue since it is not reproducible any more in the latest versions of the SDK.

Let us know if you have any further issues.

Best,
Nuno

**Comment by nuno-vieira** [comment] 2023-03-17 14:38
Hello!

This issue is now fixed in the most recent versions. The issue is quite old, so I tried to reproduce it with the most recent versions and verified it is already fixed since a lot of improvements have been made in this area.

Thank you for your patience!

Best,
Nuno

**Closed** 2024-08-14 06:56 UTC
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)
