### ISSUE TITLE
photo would randomly become very low resolution

### ISSUE THREAD

**Issue by whiplash00** [GetStream/stream-chat-swift#1541] opened 2021-10-12 18:54 UTC
## What did you do?
Send numerous photos; a small number of them will stay blurry and low resolution.

Sometimes, force-killing and reopening the app will turn other previously normal resolution photos back to low resolution.

## What did you expect to happen?
The photos should be of normal resolution.

## What happened instead?
Random photo stays low resolution.

## GetStream Environment
GetStream Chat version: 4.0.4
GetStream Chat frameworks: StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
iOS version: 15.0
Swift version: 5.5
Xcode version: 12..5.1
Device: iPhone 12 pro max
![IMG_C48502D94140-1 2](https://user-images.githubusercontent.com/16630145/137012891-0479c299-74fe-45aa-8251-e52c9bf5855b.jpeg)

**Comment by adamrushy** [comment] 2021-10-13 12:45
Thank you for reporting @whiplash00 

I am currently investigating and will come back to you :]

**Comment by kishinmanglani** [comment] 2021-11-16 12:57
This happened once for us as well recently. Someone on our team thought it was because they posted in image on web and viewed on mobile.

**Comment by nuno-vieira** [comment] 2021-12-17 18:51
@whiplash00 @kishinmanglani Is this still reproducible on the most recent versions of the SDK? 

We did try to follow all the steps and still were not able to reproduce this issue.

Thank you for your help!

**Comment by tbarbugli** [comment] 2022-01-03 10:30
@kishinmanglani good news, we finally managed to reproduce this and have a good idea on how to fix this. We will post an update soon

**Comment by polqf** [comment] 2022-01-07 14:22
@kishinmanglani this issue should be fixed now, and will be part of the upcoming release. Thank you for your report!

**Closed** 2022-01-07 14:22 UTC
Labels: bug

**Comment by polqf** [comment] 2022-01-18 16:19
We just released 4.9.0, which contains the fix for this issue: https://github.com/GetStream/stream-chat-swift/releases/tag/4.9.0
