### ISSUE TITLE
Click action on Quoted message not scrolling list to Message

### ISSUE THREAD

**Issue by SSaleemSSI** [GetStream/stream-chat-swift#2205] opened 2022-08-02 12:47 UTC
## What did you do?
I add action on replied quoted message to move the list view to respective index when user click on it but it wont move.
IndexPath always return current message index when clicked.

## What did you expect to happen?
scroll the list to top where original message is

## What happened instead?
Nothing happened

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
```
 override func messageContentViewDidTapOnQuotedMessage(_ indexPath: IndexPath?) {
        print("index path = " , indexPath!.row) // always return current message index not the QuotedMessage
        guard let indexPath = indexPath else {
           
            return log.error("IndexPath is not available")
            
        } 
        listView.scrollToRow(at: indexPath, at: .top, animated: true)
        print("tapped quoted message" , indexPath.row)
        log
            .info(
                "Tapped a quoted message. To customize the behavior, override messageContentViewDidTapOnQuotedMessage. Path: \(indexPath)"
            )
    }
```

**Comment by hugobernalstream** [comment] 2022-08-03 21:36
Hi @SSaleemSSI,

Thanks for the report. I'm reviewing the issue with the team and will come back to you soon.

Regards,
Hugo

**Comment by hugobernalstream** [comment] 2022-08-08 17:21
Hi @SSaleemSSI ,

After investigating the issue internally, `messageContentViewDidTapOnQuotedMessage(_ indexPath: IndexPath?)` indeed returns the current message index. This is not a bug per se, but we do realize we should have another method to expose the index of the quoted message. We now have an internal ticket for tracking this issue down and add this missing functionality as soon as possible.

We'll update this issue once the functionality is released in a future version.

Regards,
Hugo

**Comment by SSaleemSSI** [comment] 2022-10-13 06:42
Hi - @hugobernalstream is there any update on this issue?

**Comment by nuno-vieira** [comment] 2022-10-13 10:23
Hi @SSaleemSSI,

This is planned for Q4, we will let you know once this is released.

Best,
Nuno

**Comment by nuno-vieira** [comment] 2023-03-17 14:15
This is now fixed on the latest release! 🚀 

Thank you for your patience!

**Closed by nuno-vieira** 2023-03-17 14:15 UTC
Labels: 🔜 Upcoming, 🏗 Missing Feature Parity
