### ISSUE TITLE
Crash and Relation Failed with CoreData 

### ISSUE THREAD

**Issue by ashishrnf** [GetStream/stream-chat-swift#2533] opened 2023-03-16 09:37 UTC
Hi, I've included Stream chat in our app. However I keep getting the following crash. Thus I deduced that the cause of the crash is in your internal core data files. Please check on priority and repair it as soon as possible. This crash has impacted numerous customers.
<img width="1278" alt="Screenshot 2023-03-16 at 2 54 10 PM" src="https://user-images.githubusercontent.com/119917873/225575976-50436c70-9200-40e1-b3b2-78251c821a5a.png">

**Comment by nuno-vieira** [comment] 2023-03-16 11:38
Hi @ashishrnf,

Could you fill in the template of the Github issue since we need more context? What is the version of the SDK you are using? Do you know how to reproduce this? What are the reproducible steps? In what location of your app this happens? Do you have analytics in your app that could tell us the user journey?

Best,
Nuno

**Comment by nuno-vieira** [comment] 2023-03-16 12:29
Hi @ashishrnf,

Since 4.22.0 we have already fixed multiple stability issues related to CoreData. So we recommend updating to 4.28.0 and checking if the problem persists. Since we don't have any other customers with this specific crash, it is most likely resolved in the more recent versions. Or it can also be an integration issue of some sort. 

Recommendations:
1. **Update to 4.28.0**
2. **Provide a snippet of how you use the `addDevice()` API in your APP.** 

Best,
Nuno

**Comment by ashishrnf** [comment] 2023-03-16 12:58
Hi Nuno,
I will update the SDK's with latest one. for you information I have attached snapshot of addDevice() API which is using in our App.
<img width="664" alt="Screenshot 2023-03-16 at 6 26 14 PM" src="https://user-images.githubusercontent.com/119917873/225623841-6ff7d153-6626-42f9-aa0d-45b438ae00c3.png">

**Comment by nuno-vieira** [comment] 2023-03-16 13:41
Hi @ashishrnf!

Thanks for the snippet. Where is this called? Inside `didRegisterForRemoteNotificationsWithDeviceToken`? Is snippet directly called when `didRegisterForRemoteNotificationsWithDeviceToken` is called, or do you do an API call before or something? I'm trying to understand if the `addDevice` is called from a different thread. 

Best,
Nuno

**Comment by nuno-vieira** [comment] 2023-03-17 10:08
Hi @ashishrnf,

Let us know if you still have this crash in 4.28.0. 

I'm closing the issue, but please re-open it if you still have the crash.

Best,
Nuno

**Closed by nuno-vieira** 2023-03-17 10:08 UTC
Labels: 🔎 Investigating

**Comment by ashishrnf** [comment] 2023-03-17 10:23
@nuno-vieira sure.

**Comment by aryalg** [comment] 2023-03-22 11:23
Still facing issue

**Comment by ashishrnf** [comment] 2023-03-23 05:27
Hi Aryalg,
The binary has not yet been published to the Appstore. I will notify you when the app is ready.

**Comment by ashishrnf** [comment] 2023-04-27 07:13
Hi,
Channel is being create with name but when we create more than 10, 20 channel continuously then it create random one channel without name. so here my logic integration is right. otherwise it create channel without name every time. although I am giving information below of channel creation. So please check and tell me what is missing in this logic.
first make api call and getting response from server :
{
"message" : "Direct message created successfully",
"is_exist" : false,
"status" : 200,
"id" : "921486c0-d1f6-4fb7-abf5-4abc0ef24464"
}
Then we this id we send to Stream Chat for creating channel/DM code is given below:
let chatScreen = ChatChannelViewController()
chatScreen.channelController = ChatClient.shared?.channelController(for: ChannelId.init(type: .messaging, id: JSONResponse["id"].stringValue))
chatScreen.isFromCreate = true
chatScreen.eType = .messaging
self.navigationController?.pushViewController(chatScreen, animated: true)

Here ChatChannelViewController extend Stream ChatChannelVC such type
class ChatChannelViewController: ChatChannelVC {

}

Please Check Direct Message with out name occurs 5 times out of 100. actual this is core data related issue from stream side. continuous creating channel some time stream is unable to save this Direct message Data and giving nil value so it display Direct message without name. So please check it.
Thanks
Ashish Tiwari

**Comment by polqf** [comment] 2023-04-27 07:38
@ashishrnf please refrain from posting the same message in different issues. The message above corresponds to https://github.com/GetStream/stream-chat-swift/issues/2582
