### ISSUE TITLE
Version installed is different than pod version (console warning)

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-swift#416] opened 2020-08-19 23:59 UTC
I'm on the latest StreamChatClient pod:

```
  - StreamChatClient (2.2.9):
    - Starscream (~> 3.1)
```

However, when I launch the app and configure the client I get the following warning in the console telling me to upgrade the client:

```
[19 Aug 19:57:55.950] [INFO] StreamChat 2.2.9 is released (you are on 1.22.0). It's recommended to update to the latest version.
```

Is there any way to resolve this?

gz#5433

**Comment by b-onc** [comment] 2020-08-24 10:11
Hello @amardeepranu 
I cannot reproduce the issue. Are you still seeing this behavior?

**Comment by amardeepranu** [comment] 2020-08-24 12:44
I think I found the issue. In the Stream chat client code, in `Environment.swift`

```
/// A Stream Chat version.
    public static let version: String = Bundle(for: Client.self).infoDictionary?["CFBundleShortVersionString"] as? String ?? "0.0.0"
```

It's pulling MY app's version which is 1.22.0, not the version of the client.

**Comment by VojtaStavik** [comment] 2020-08-24 13:12
@amardeepranu Thank you for debugging the problem. How do you include the SDK to your project?

**Comment by amardeepranu** [comment] 2020-08-24 13:14
@VojtaStavik Cocoapods

```
  pod 'StreamChatClient'
```

**Comment by amardeepranu** [comment] 2020-08-24 13:19
This is the only custom script I have:
```
# Build for all architectures (not just the active one)
# and set the deployment target of the pods
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
    end
    add_acknowledgments_to_settings_bundle
end
```

**Comment by VojtaStavik** [comment] 2020-08-24 13:24
That doesn't seem to do anything related to the version number. However, It would be worth to try to re-install the pods without this script. Just to be sure nothing strange is happening there and we can cross out this option.

**Comment by amardeepranu** [comment] 2020-08-24 13:39
Reinstalled and still getting the console error

**Comment by VojtaStavik** [comment] 2020-08-24 13:40
OK, thank you for confirming that. Will continue exploration on our side.

**Comment by b-onc** [comment] 2021-03-12 16:15
Hello,

Thanks a lot for reporting this issue. We now have resolved this and false-positive warnings are no longer logged to console. The fix is in the latest version (3.x), so we suggest upgrading. Please re-open if you see this issue happening again.

**Closed by b-onc** 2021-03-12 16:15 UTC
Labels: question
