### ISSUE TITLE
Photo viewer dismissal animation is totally off for a photo taken from iPhone 13 Pro

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swift#1804] opened 2022-02-20 05:17 UTC
https://user-images.githubusercontent.com/97132583/154829341-e32f7cdf-a2d5-4295-b234-b44a21bd6779.mp4

See attached video. I tapped on a photo from ChatChannelView, and dismissed it. For most photos, the animation works perfectly fine ... but today after sending a photo from my iPhone 13 Pro, I noticed that the dismissal animation looks totally wonky.

Some other information that may help you debug/scope:
1. I took a screenshot on the same phone and sent it. The bug doesn't repro. The dismissal animation is totally fine.
2. I went to iOS's Photos app and cropped the "bad" photo by a few pixels at bottom and right. Lo and behold .. the bug goes away! No idea why.

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS 15.3.1
**Swift version:**
**Xcode version:**
**Device:** iPhone 13 Pro

**Comment by linhewinner** [comment] 2022-02-20 05:42
I see that this may be similar to this issue:
https://github.com/GetStream/stream-chat-swift/issues/1588

That issue seems to have stalled because it's so difficult to reproduce.

I suggest that you guys try an iPhone 13 Pro (the bug repros for me with or without Live photos), and see if you can easily repro.
If you still can't repro ... I am happy to do some debugging and let you know what the root cause is.

**Comment by linhewinner** [comment] 2022-03-17 20:05
I was excited to see 4.12.0 released but .... a bit disappointed that this bug wasn't fixed.

This has become our worst and most user-visible bug (since a lot of people use iPhone 13 and all the photos were literally flying randomly on the screen all the time).

Before I sink my teeth into copy-pasting and rewriting ZoomAnimator and ZoomDismissalTransitionController ... I am wondering if this is coming soon-ish?

**Comment by nuno-vieira** [comment] 2022-03-18 12:56
Hi @linhewinner!

We do want to refactor the ZoomAnimator and ZoomDismissalTransitionController since they are overly complex at the moment, and we plan to fix this issue, but at the moment this is not our most priority issue so I'm afraid it won't be coming out soon-ish, at least not in the coming weeks. 

Do you have a way to measure how is this impacting your customers? Why do you think this is your worst bug at the moment?

If you do want to fix the issue yourself there is no need to copy-pasting and rewrite the ZoomAnimator in your app. We do accept pull requests from everyone. Feel free to open a PR if you have already an idea on how to fix the issue and if you have the time to do it of course! We do appreciate a lot the help and review of all the PRs. 

Best,
Nuno

**Comment by nuno-vieira** [comment] 2022-04-11 14:17
Duplicate of: https://github.com/GetStream/stream-chat-swift/issues/1588

This issue will be available in the next release.

Thank you!
Nuno

**Comment by bielikb** [comment] 2022-04-26 12:43
Hi @linhewinner,

we just released [new version of our SDK 4.14.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.14.0) that contains the fix for your reported issue.

Feel free to try it out!

Thanks again for your help! 🙌

Best,
Boris

**Closed by bielikb** 2022-04-26 12:43 UTC
Labels: 🐞 Bug, 2️⃣ Duplicate, 🎨 SDK: StreamChatUI, 🔜 Upcoming
