### ISSUE TITLE
ChannelList change index after pagination

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2522] opened 2023-02-15 11:22 UTC
- Let's say, I initially loaded 5 channels.
- For the next channels, I called `checkForChannels` from `ChatChannelListViewModel`
- It will fetch the next N channels. But, instead of appending the next channels after already fetched channels, it appends between them.
- e.g. I have the first 5 channels. Initial channels will be [0,1,2,3,4,5]
- After pagination, the channels look like this [0,1,2,3,6,7,8,9,10,4,5]
- The channels index should consistence even after pagination.

ChannelList query that I am using:

```
chatClient.channelListController(
            query: .init(
                filter: .or([
                    .and([
                        .equal(.type, to: "X"),
                        .nonEmpty,
                    ]),
                    .and([
                        .equal(.type, to: "Y"),
                        .nonEmpty,
                    ]),
                    .and([
                        .containMembers(userIds: [currentUserID]),
                        .nonEmpty,
                    ]),
                ]),
                sort: [.init(key: .lastMessageAt, isAscending: false)],
                pageSize: 10,
                messagesLimit: 1
            ), filter: { channel in
                if channel.lastMessageAt == nil {
                     return false
                }
                switch channel.type {
                case ChannelType.custom("X"):
                    return true
                case ChannelType.custom("Y"):
                    if ChatClient.shared.currentUserController().currentUser?.userRole == UserRoleCustomType.A.value {
                        return true
                    } else {
                        return channel.membership != nil
                    }
                default:
                    return channel.membership != nil
                }
            }
        )
```

## GetStream Environment
**GetStream Chat version:** 4.26.0
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** Xcode 14.2
**Device:** Iphone X

**Comment by martinmitrevski** [comment] 2023-03-03 14:57
Moving this to our low-level client repo - it seems it's not connected to the SwiftUI SDK.

**Comment by ipavlidakis** [comment] 2023-03-03 15:23
Hi @ajay-simform 

Another thing that looks suspicious is the filter closure you are providing. The filter close should be matching fully or partially the filter. In your case, I can see that you are filtering based on the user's role (our [docs](https://getstream.io/chat/docs/ios-swift/channel_capabilities/?language=swift) mentions that filtering based on the user's role is not recommended) and the membership. Both cases may cause issues.

I'm wondering if something like the following will help resolve the issue that you have
```swift
query: .init(
    filter: .and([
        .or([
            .equal(.type, to: .custom("X")),
            .equal(.type, to: .custom("Y")),
            .containMembers(userIds: [currentUserID]) // I believe that this may be unnecessary as the API always returns the channels that the currentUser is a member
        ]),
        .nonEmpty
    ]),
    sort: [.init(key: .lastMessageAt, isAscending: false), .init(key: .createdAt, isAscending: false)],
    pageSize: 10,
    messagesLimit: 1
), filter: { channel in
    switch channel.type {
    case ChannelType.custom("X"):
        return true
    case ChannelType.custom("Y"):
        return ChatClient.shared.currentUserController().currentUser?.userRole == UserRoleCustomType.A.value
    default:
        return false
    }
}
```

If you can try the code above and let us know the outcome, it may help us find the path towards a solution to the initial issue.

Best regards,
Ilias

**Comment by ajay-simform** [comment] 2023-03-06 09:05
Hi @ipavlidakis ,

The query filter condition without containMember is necessary. I have multiple channels; in some channels, I want to show all the created channels without filtering out whether the user is a member or not. e.g. you can see channel types "X" and "Y" in my query.
```
filter: .or([
                    .and([
                        .equal(.type, to: "X"),
                        .nonEmpty,
                    ]),
                    .and([
                        .equal(.type, to: "Y"),
                        .nonEmpty,
                    ]),
                    .and([
                        .containMembers(userIds: [currentUserID]),
                        .nonEmpty,
                    ]),
                ]),
```

Also, I tried the suggested query [[here](https://github.com/GetStream/stream-chat-swift/issues/2522#issuecomment-1453693891)] but still facing the same [issue](https://github.com/GetStream/stream-chat-swift/issues/2522#issuecomment-1453652482).

Thanks

**Comment by ipavlidakis** [comment] 2023-03-06 14:35
Hi @ajay-simform 

Just to help us exclude possible causes do you mind setting `isChannelAutomaticFilteringEnabled` variable to false in your ChatClientConfiguration like the following example:
```swift
var config = ChatClientConfig(apiKeyString: <YOUR API KEY>)
config.isChannelAutomaticFilteringEnabled = false
... (any other configuration you may have)

let client = ChatClient(config: config)
```
and then try your original query.

Thanks,
Ilias

**Comment by ajay-simform** [comment] 2023-03-10 12:48
Hi @ipavlidakis ,
I tried adding `isChannelAutomaticFilteringEnabled = false` in the config. But still facing the same issue.
Thanks.

**Comment by nuno-vieira** [comment] 2023-03-13 22:19
Hi @ajay-simform,

Can you update the SDK to version 4.28.0 and check if the issue is still present?

Another question I have is, why are you providing custom sorting? The sorting you are providing seems to be the default one. Can you try removing the `sort` parameter and see if everything works as you expected?

Thanks,
Nuno

**Comment by ajay-simform** [comment] 2023-03-17 12:52
Hi @nuno-vieira 
I removed `sort` parameter as you suggested and update SDK with version 4.28.0 but still facing the same [issue](https://github.com/GetStream/stream-chat-swift/issues/2522#issuecomment-1453652482).

**Comment by nuno-vieira** [comment] 2023-03-17 14:26
Hi @ajay-simform!

Thank you, we were able to reproduce this on our end in some scenarios as well. 

We will prioritise this one internally and will let you know once we pick pick it up 👍 

Best,
Nuno

**Comment by abhi-m-simformsolutons** [comment] 2023-04-06 13:37
Hi @nuno-vieira ,

Can you please provide me with an update on the current status of the issue? I am eager to know if there have been any developments or if there is an estimated timeline for a resolution.

Thank you for your assistance in this matter. I look forward to hearing from you soon.

Best,
Ajay

**Comment by nuno-vieira** [comment] 2023-04-06 14:12
One last question for you, @ajay-simform. Does the issue still happen when all channels have messages? Can you try testing in a scenario where all channels have at least one message? (This will help us speeding up the time to fix this) 

Thank you,
Nuno

**Comment by ajay-simform** [comment] 2023-04-11 08:09
Hi @nuno-vieira ,
I checked with the channels having messages. But the issue still happens. Also, I created a ticket on the support page to prioritise the issue.

Thank you.

**Comment by polqf** [comment] 2023-06-09 11:52
Closing this issue here as it is being tackled through support

**Closed by polqf** 2023-06-09 11:52 UTC
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC)
