### ISSUE TITLE
StreamChatUI SDK freeze issue while selecting any channel. 

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-swift#955] opened 2021-04-05 12:53 UTC
## What did you do?
just tapped on any channel.

## What did you expect to happen?
This should open a channel for chat. 

## What happened instead?
App is freezing while selecting any channel, I saw some infinite logs printing on console, see SS attached.

## GetStream Environment
**GetStream Chat version:** 3.1.4
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 13.0
**Swift version:** 5.3
**Xcode version:** 12.2
**Device:** iPhone XR simulator
<img width="1051" alt="Screenshot 2021-04-05 at 6 17 20 PM" src="https://user-images.githubusercontent.com/54673061/113575765-fefa8580-963b-11eb-8160-1dbe1fc13cfa.png">

**Comment by iosiappmemes** [comment] 2021-04-07 09:37
Hey Stream team, I been waiting for your response.

**Comment by VojtaStavik** [comment] 2021-04-08 20:22
Hi @iosiappmemes, can you provide more information? Did you perform any layout changes?

**Comment by iosiappmemes** [comment] 2021-04-09 05:44
No, I just used inbuilt UI provided by StreamChatUI SDK .

**Comment by iosiappmemes** [comment] 2021-04-09 05:47
I used ChannelListVC to display list of channel. as you can see in SS, I just click on channel it freezes the app and it started printing log infinitely on console as shown in SS.

**Comment by varindersingh007** [comment] 2021-04-12 07:14
@iosiappmemes , facing same issue.

**Comment by varindersingh007** [comment] 2021-04-12 12:01
Stream Team, I have updated SDK from 3.1.4 to 3.1.5 , still facing same app freeze issue.

**Comment by VojtaStavik** [comment] 2021-04-12 12:03
@varindersingh007 @iosiappmemes We're failing to reproduce this. Any chance you can share a sample project (or just the VC class) where this happens?

**Comment by iosiappmemes** [comment] 2021-04-12 12:08
@VojtaStavik , ok let me check the possibility, updating in a moment.

**Comment by varindersingh007** [comment] 2021-04-12 12:48
Hi @VojtaStavik , Let me tell you my exact issue.
I am using **UITabbarController** to add **ChatChannelListVC** . its working fine . I am able to add ChatChannelListVc in TabbarController. but when I am trying to click on chat app freezes there. 
In the second case i am not adding ChatChannelListVC in TabbarController.
I am just pushing ChatChannelListVC from some controller . Then its working fine , I am able to chat with others .
The Point is how to use ChatChannelListVc by using UITabbarController ?

**Comment by varindersingh007** [comment] 2021-04-12 12:57
What if **ChatClient** Not connected yet, and user clicked on ChatChannelListVC tab in **UITabbarController**. 
As **ChatChannelListVC** needs a **ChatChannelListController** to assign with currentUserID. 
What to do if we don't have user id Yet, because we can't initialize c **ChatChannelListController**.
So in this case what to assign to  **ChatChannelListVC**.

**Comment by varindersingh007** [comment] 2021-04-12 13:00
![Screen Shot 2021-04-12 at 6 29 52 PM](https://user-images.githubusercontent.com/67784123/114398144-1649ed80-9bbd-11eb-88a2-00d7be5463de.png)

**Comment by varindersingh007** [comment] 2021-04-15 05:11
Hi @VojtaStavik , still waiting for your response.

**Comment by VojtaStavik** [comment] 2021-04-16 10:05
@varindersingh007 is there's anything specific you do with the VC? I tried to replicate but no luck so far.

**Comment by b-onc** [comment] 2021-05-12 13:03
Hey @varindersingh007 and @iosiappmemes , are you seeing this issue in the latest version? We cannot reproduce.

**Comment by b-onc** [comment] 2021-06-01 18:42
Closing due to inactivity

**Closed by b-onc** 2021-06-01 18:42 UTC
Labels: question
