### ISSUE TITLE
Invalid number of rows in section 0.

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#171] opened 2020-04-10 20:00 UTC
## What did you do?
Open a Chat View:

```
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (92) must be equal to the number of rows contained in that section before the update (88), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
```

```
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1abfb096c __exceptionPreprocess
1  libobjc.A.dylib                0x1abcc9028 objc_exception_throw
2  CoreFoundation                 0x1abead4fc +[_CFXNotificationTokenRegistration keyCallbacks]
3  Foundation                     0x1ac2ee690 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKitCore                      0x1b026b900 -[UITableView _Bug_Detected_In_Client_Of_UITableView_Invalid_Number_Of_Rows_In_Section:]
5  UIKitCore                      0x1b026b3b4 -[UITableView _endCellAnimationsWithContext:]
6  UIKitCore                      0x1b0282824 -[UITableView endUpdatesWithContext:]
7  UIKitCore                      0x1b02829f8 -[UITableView _performBatchUpdates:withContext:completion:]
8  UIKitCore                      0x1b0282b68 -[UITableView performBatchUpdates:completion:]
9  StreamChat                     0x1096d7640 closure #1 in ChatViewController.updateTableView(with:) (<compiler-generated>)
10 StreamChat                     0x1096df188 partial apply for thunk for @callee_guaranteed () -> () (<compiler-generated>)
11 StreamChat                     0x1096ab080 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
12 UIKitCore                      0x1b0556d54 +[UIView(Animation) performWithoutAnimation:]
13 StreamChat                     0x1096d2844 ChatViewController.updateTableView(with:) (<compiler-generated>)
14 StreamChat                     0x1096de2c8 partial apply for closure #4 in ChatViewController.viewDidLoad() (<compiler-generated>)
15 StreamChat                     0x109662354 thunk for @escaping @callee_guaranteed (@guaranteed ViewChanges) -> () (<compiler-generated>)
16 RxSwift                        0x10929eae8 closure #1 in ObservableType.subscribe(onNext:onError:onCompleted:onDisposed:) (<compiler-generated>)
17 RxSwift                        0x10929ece8 partial apply for closure #1 in ObservableType.subscribe(onNext:onError:onCompleted:onDisposed:) (<compiler-generated>)
18 RxSwift                        0x109251658 AnonymousObserver.onCore(_:) (<compiler-generated>)
19 RxSwift                        0x1092a1544 ObserverBase.on(_:) + 16 (ObserverBase.swift:16)
20 RxSwift                        0x1092a1700 protocol witness for ObserverType.on(_:) in conformance ObserverBase<A> (<compiler-generated>)
21 RxSwift                        0x1092a1b10 partial apply (<compiler-generated>)
22 RxSwift                        0x1092bdd3c partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Event<A>) -> () (<compiler-generated>)
23 RxSwift                        0x1092bcc24 ShareReplay1WhileConnectedConnection.on(_:)
24 RxSwift                        0x1092bc750 protocol witness for ObserverType.on(_:) in conformance ShareReplay1WhileConnectedConnection<A> (<compiler-generated>)
25 RxSwift                        0x1092c13f0 Sink.forwardOn(_:) + 35 (Sink.swift:35)
26 RxSwift                        0x10928d7f0 FilterSink.on(_:) + 62 (Filter.swift:62)
27 RxSwift                        0x10928d924 protocol witness for ObserverType.on(_:) in conformance FilterSink<A> (<compiler-generated>)
28 RxSwift                        0x1092a1b10 partial apply (<compiler-generated>)
29 RxSwift                        0x1092bdd3c partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Event<A>) -> () (<compiler-generated>)
30 RxSwift                        0x1092bcc24 ShareReplay1WhileConnectedConnection.on(_:)
31 RxSwift                        0x1092bc750 protocol witness for ObserverType.on(_:) in conformance ShareReplay1WhileConnectedConnection<A> (<compiler-generated>)
32 RxSwift                        0x1092c13f0 Sink.forwardOn(_:) + 35 (Sink.swift:35)
33 RxSwift                        0x1092c68a0 SwitchSinkIter._synchronized_on(_:) + 171 (Switch.swift:171)
34 RxSwift                        0x1092c7cd8 SynchronizedOnType.synchronizedOn(_:) + 15 (SynchronizedOnType.swift:15)
35 RxSwift                        0x1092c66d0 SwitchSinkIter.on(_:) + 145 (Switch.swift:145)
36 RxSwift                        0x1092c6954 protocol witness for ObserverType.on(_:) in conformance SwitchSinkIter<A, B, C> (<compiler-generated>)
37 RxSwift                        0x1092a1b10 partial apply (<compiler-generated>)
38 RxSwift                        0x1092bdd3c partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Event<A>) -> () (<compiler-generated>)
39 RxSwift                        0x1092bcc24 ShareReplay1WhileConnectedConnection.on(_:)
40 RxSwift                        0x1092bc750 protocol witness for ObserverType.on(_:) in conformance ShareReplay1WhileConnectedConnection<A> (<compiler-generated>)
41 RxSwift                        0x1092c13f0 Sink.forwardOn(_:) + 35 (Sink.swift:35)
42 RxSwift                        0x109299e80 MergeSinkIter.on(_:) + 394 (Merge.swift:394)
43 RxSwift                        0x10929a004 protocol witness for ObserverType.on(_:) in conformance MergeSinkIter<A, B, C> (<compiler-generated>)
44 RxSwift                        0x1092a1b10 partial apply (<compiler-generated>)
45 RxSwift                        0x1092bdd3c partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Event<A>) -> () (<compiler-generated>)
46 RxSwift                        0x1092bcc24 ShareReplay1WhileConnectedConnection.on(_:)
47 RxSwift                        0x1092bc750 protocol witness for ObserverType.on(_:) in conformance ShareReplay1WhileConnectedConnection<A> (<compiler-generated>)
48 RxSwift                        0x1092c13f0 Sink.forwardOn(_:) + 35 (Sink.swift:35)
49 RxSwift                        0x10925e5e8 CatchSink.on(_:) + 131 (Catch.swift:131)
50 RxSwift                        0x10925e8d4 protocol witness for ObserverType.on(_:) in conformance CatchSink<A> (<compiler-generated>)
51 RxSwift                        0x1092a095c closure #1 in ObserveOnSerialDispatchQueueSink.init(scheduler:observer:cancel:) + 186 (ObserveOn.swift:186)
52 RxSwift                        0x1092a1250 partial apply for thunk for @escaping @callee_guaranteed (@guaranteed ObserveOnSerialDispatchQueueSink<A>, @in_guaranteed Event<A.Element>) -> (@out Disposable) (<compiler-generated>)
53 RxSwift                        0x1092944b8 closure #1 in MainScheduler.scheduleInternal<A>(_:action:) + 72 (MainScheduler.swift:72)
54 RxSwift                        0x10927a398 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
55 libdispatch.dylib              0x1abc54b7c _dispatch_call_block_and_release
56 libdispatch.dylib              0x1abc55fd8 _dispatch_client_callout
57 libdispatch.dylib              0x1abc61cc8 _dispatch_main_queue_callback_4CF
58 CoreFoundation                 0x1abf2bcc8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
59 CoreFoundation                 0x1abf26a24 __CFRunLoopRun
60 CoreFoundation                 0x1abf25f40 CFRunLoopRunSpecific
61 GraphicsServices               0x1b61b6534 GSEventRunModal
62 UIKitCore                      0x1b00b1580 UIApplicationMain
63 OURAPP                      0x1047978dc main + 33 (AppDelegate.swift:33)
64 libdyld.dylib                  0x1abda4e18 start
```

**Comment by b-onc** [comment] 2020-04-24 11:42
Hello @khoogheem 
Can you consistently reproduce the issue? Is it for a specific user/channel?

**Comment by khoogheem** [comment] 2020-04-24 12:03
I have not been able to myself.. but we have had a handful of these crash reports.  With no specific rhyme or reason.

**Comment by b-onc** [comment] 2020-06-23 15:47
@khoogheem Do you have new reports/info you can provide for solving this issue?

**Comment by khoogheem** [comment] 2020-06-23 16:16
none... and have not seen crash reports of this in a few weeks.
now running 2.2.4

**Comment by b-onc** [comment] 2020-06-23 17:52
Thanks for the info. I'm closing the issue due to non-reproducibility

**Closed by b-onc** 2020-06-23 17:52 UTC
Labels: bug, question, sdk:ui
