### ISSUE TITLE
synchronize() callback sometimes never fires for new chats

### ISSUE THREAD

**Issue by remvst** [GetStream/stream-chat-swift#2524] opened 2023-03-08 15:56 UTC
## What did you do?

Created a new chat with an individual user:

```swift
channelController = try client.channelController(
    createDirectMessageChannelWith: [currentUserId, remoteAccountId],
    type: .messaging,
    extraData: [:]
)

log(.....) // this gets reached
channelController!.synchronize { [weak self] error in
     log(.......) // logging something regardless of success or failure <- THIS NEVER GETS REACHED
}
```

## What did you expect to happen?

The callback passed to `synchronize()` should eventually get called, with an error or a success.

## What happened instead?

The callback is never called, causing users to be stuck in an infinite loading state.

## GetStream Environment
**GetStream Chat version:** 4.24.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15
**Swift version:** `swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)`
**Xcode version:** `Version 14.1 (14B47b)`
**Device:** any iOS device

## Additional context

- We have not found a consistent repro for this issue, but we've identified that it happens for new chats (intermittently). 
- `log()` calls indicate that `synchronize()` is getting called, however the callback doesn't get reached
- Our production metrics indicate that a non-negligible amount of our users is impacted by this issue. While in most cases the callback gets fired as expected, we would like to resolve this issue

**Comment by alteral** [comment] 2023-03-08 17:28
Hi @remvst,

Thank you for reporting this issue. We'll do the investigation on our end and reply to this ticket when there is any news.
In the meantime, I see you are using StreamChat `4.24.0`. Can I ask you to update the version to `4.28.0` and confirm that the issue is still there?

Best,
Alex

**Comment by alteral** [comment] 2023-03-08 17:58
I see. Another quick question then, did it start happening straight after updating to `4.24.0` or you've just noticed it recently?

**Comment by remvst** [comment] 2023-03-08 18:37
> I see. Another quick question then, did it start happening straight after updating to `4.24.0` or you've just noticed it recently?

`4.24.0` is the first (and only) version that we shipped to our users, so unfortunately I can't say whether this is a regression or a behavior that was always there.

**Comment by alteral** [comment] 2023-03-09 15:58
@remvst, it seems the issue is with expired tokens, and in `4.25.0` is when we added the retries mechanism for those. So, upgrading to `4.25.0` should fix your issue, but I would suggest upgrading straight to `4.28.0`, because we've implemented many improvements since then.

**Comment by alteral** [comment] 2023-03-09 16:07
@remvst, I'm going to close the issue for now. If updating the StreamChat version won't help, feel free to reopen this ticket.

Best,
Alex

**Closed by alteral** 2023-03-09 16:07 UTC
