### ISSUE TITLE
New messages aren't marked as read when inside a chat

### ISSUE THREAD

**Issue by nicol3a** [GetStream/stream-chat-swift#897] opened 2021-03-18 13:08 UTC
## What did you do?
I'm inside a chat (`ChatViewController` subclass) and I receive a new message.

## What did you expect to happen?
The new message is instantly marked as read.

## What happened instead?
The new message is only marked as read when I enter the chat. If I'm already inside the chat and I receive a new message, it's never marked as read. I have to go back and re-enter the chat again to mark the new message as read.

## GetStream Environment
**GetStream Chat version:** 2.6.4
**GetStream Chat frameworks:** StreamChat 2.6.4, StreamChatClient 2.6.4, StreamChatCore 2.6.4
**iOS version:** iOS 14.4
**Swift version:** Swift 5
**Xcode version:** Xcode 12.4
**Device:** Simulator, iPhone Xs

## Additional context
Here's what I found:

In ChannelPresenter+RxRequests, l. 123, when I receive a new message, the `base.channel.readEventsEnabled` property is equal to `false`. So the new message is not marked as read.

```swift
func markReadIfPossible() -> Observable<StreamChatClient.Event> {
  guard InternetConnection.shared.isAvailable, base.channel.readEventsEnabled else {
    return .empty()
  }
  // ...
}
```

The `readEventsEnabled` value is equal to this:
```swift
public var readEventsEnabled: Bool { config.readEventsEnabled && membership != nil }
```

The problem is the `membership` property is `nil`, while the 2 users are members of the channel. Plus, it works when I enter the chat. So my guess is the `Channel` object is reinitialized somewhere without a `Membership` object. I don't know where.

The only place the `membership` can be initialized right now is in the `ChannelResponse` class. I put some breakpoints in it, and when I receive a new message, this code is not called.

Maybe I'm not initializing the chat correctly? I'm not using `ChannelsViewController`. I directly instantiate a `ChatViewController` subclass object.

```swift
let channel = Channel(
  type: .messaging,
  id: channelId,
  members: users,
  invitedMembers: [],
  extraData: nil,
  created: Date(),
  deleted: nil,
  createdBy: nil,
  lastMessageDate: nil,
  frozen: false,
  config: Channel.Config()
)

let chatViewController = StreamChatViewController() // Subclass of ChatViewController
chatViewController.presenter = ChannelPresenter(channel: channel)
```

**Comment by b-onc** [comment] 2021-03-24 14:08
Hello @nicol3a 
Please use `Client.shared.channel(type:id:)` function to generate the channel, not the `Channel` init. Does it work correctly when you do it?

**Comment by nicol3a** [comment] 2021-03-24 16:14
Hello @b-onc, and thank you for your answer,
I have the same problem, even if I use `Client.shared.channel(type:id:)` though.
Any other idea?

**Comment by nicol3a** [comment] 2021-03-24 18:45
I even tried to use the `ChannelsViewController` class and it still doesn't work.

```swift
let channelsViewController = ChannelsViewController()
channelsViewController.presenter = ChannelsPresenter(filter: .currentUserInMembers)
```

I think it's a bug in the SDK. Because all messages are marked as read when I enter the channel, which means the configuration is valid, the `membership` channel property is not nil.

But then when I receive new messages and I'm still in the channel, the new messages aren't marked as read.

**Comment by nicol3a** [comment] 2021-04-01 14:04
FYI, I found a temporary fix by commenting some lines in the Stream SDK.

In `StreamChatClient/Channel.swift`:
```swift
public var readEventsEnabled: Bool { config.readEventsEnabled/* && membership != nil*/ }
```

And in `StreamChatCore/ChannelPresenter+RxRequests`:
```swift
func markReadIfPossible() -> Observable<StreamChatClient.Event> {
    guard InternetConnection.shared.isAvailable, base.channel.readEventsEnabled else {
        return .empty()
    }

//    guard base.channel.isUnread else {
//        Client.shared.logger?.log("🎫↩️ Skip mark read. \(base.channel.unreadCount) at "
//            + (base.channel.unreadMessageRead?.lastReadDate.description ?? "<NoLastReadDate>"))
//        return .empty()
//    }

    return Observable.just(())
        .subscribeOn(MainScheduler.instance)
        .filter { UIApplication.shared.applicationState == .active }
        .flatMapLatest { [weak base] in base?.channel.rx.markRead() ?? .empty() }
}
```

As a result, each time a new message is received while I'm inside a chat, it is automatically marked as read. Commenting the `guard` may result in too many calls, but at least it works.

**Comment by b-onc** [comment] 2021-05-12 13:12
Hello @nicol3a ,

This should be fixed with commit `f918fdaa5afe503e3962aa4a383687273f3bb5a0`, as I try I cannot reproduce this on the latest `main_v2`. Can you try and let me know if it works?

**Comment by nicol3a** [comment] 2021-05-13 20:00
Hello @b-onc ,

I just tested it and it still doesn't work.

**Comment by b-onc** [comment] 2021-05-18 12:07
Hello @nicol3a ,

As I can't reproduce the issue, can you please share an example project for me to work on?

**Comment by b-onc** [comment] 2021-06-14 12:57
Closing due to inactivity

**Closed by b-onc** 2021-06-14 12:57 UTC
Labels: bug, sdk:StreamChat(v2)
