### ISSUE TITLE
ChatMessage.replyCount is not correct when quoting parent message

### ISSUE THREAD

**Issue by EuyjaeHwang** [GetStream/stream-chat-swift#1806] opened 2022-02-21 07:11 UTC
## What did you do?
I watched message list by using ChatChannelController
```Swift
channelController = client.channelController(for: cid)
channelController.messagesChangesPublisher.map { ... }
```
And I send a reply to a message

## What did you expect to happen?
I expected the value of `ChatMessage.replyCount` to be correct value. Always

## What happened instead?
```Swift
func channelController(
    _ channelController: ChatChannelController,
    didUpdateMessages changes: [ListChange<ChatMessage>]
) { ... }
```
`ChatMessage.replyCount` value comes with the previous value.
for example, when I write first reply on the message, the message's reply count not changes(expected to be 1).
but when I add one more reply on it, reply count changes to 1 (expected to be 2).
and then I add one more reply on it, reply count changes to 2 (expected to be 3).
please see the video clip above for demo.
thanks 👍

## GetStream Environment
**GetStream Chat version:** 4.6.0
**GetStream Chat frameworks:** StreamChat
**iOS version:** 15.x, 14.x
**Swift version:** 5.1
**Xcode version:** 13.2.1
**Device:** all of iPhone, iPad supporting iOS 14+

## Additional context

https://user-images.githubusercontent.com/52391488/154905975-a40f43fa-6b5e-423a-913d-d6ed7b0c8337.mov

**Comment by bielikb** [comment] 2022-02-21 11:12
Hi @EuyjaeHwang,

thanks for the report. Im going to check if this issue is still reproducible in our latest release 4.10.1 and will come back to you.

Best,
Boris

**Comment by EuyjaeHwang** [comment] 2022-02-24 04:32
I didn't use a StreamChatUI SDK. I'm just using a StreamChat SDK. 😅

**Comment by b-onc** [comment] 2022-02-25 14:08
Hello @EuyjaeHwang ,

I wasn't able to reproduce this issue with the latest SDK version (4.10.1)

What I did:
1. I've overridden the `didUpdateMessagesFunction` like so:
```swift
override func channelController(_ channelController: ChatChannelController, didUpdateMessages changes: [ListChange<ChatMessage>]) {
        super.channelController(channelController, didUpdateMessages: changes)
        changes.forEach {
            log.warning("Message text \($0.item.text) replyCount \($0.item.replyCount)")
        }
    }
```
2. I've thread replied to a message and observed the logs.

There are 3 update logs:
1. Message is inserted into the DB with `pendingSend`
2. Message is being sent, so becomes `sending`
3. Message is successfully sent, so becomes `state == nil`

The replyCount is correct for the last update (when `state` is `nil`), so all is expected. The original message's `replyCount` is not updated until the reply is successfully sent to backend.

**Comment by EuyjaeHwang** [comment] 2022-03-04 05:30
Hmm... I updated SDK version (4.10.1) but still replyCount is not correct....
`messagesChangesPublisher` published previous replyCount 🤔

**Comment by b-onc** [comment] 2022-03-04 13:26
Hello @EuyjaeHwang ,

When you test with the delegate funcs (like I've pasted above), do you see the issue happening? I'm trying to understand if the issue is within combine publishers or within the data update mechanism.

**Comment by tokirin** [comment] 2022-03-07 09:28
Hello, I'm team mate with @EuyjaeHwang.
I recorded debugging screen with above bug.
I use 4.10.1 SDK and use delegate as you mentioned.
Please check this [linked video](http://gofile.me/4jHDt/9jEptJIbZ)

> this video file is so huge(over 500mb) so I uploaded my NAS

Sincerely

**Comment by b-onc** [comment] 2022-03-07 13:37
Hello @tokirin ,

See the screenshot from the video you've sent:
<img width="1272" alt="Screen Shot 2022-03-07 at 14 35 27" src="https://user-images.githubusercontent.com/770464/157044507-d965cd4b-1086-4480-acd6-3036cc4f2f43.png">

replyCount does get updated, but not in the first update. This is expected since multiple updates happen when a reply is sent.

There are 3 updates:
Reply Message is inserted into the DB with pendingSend (original message's replyCount is not updated at this point)
Reply Message is being sent, so becomes sending (original message's replyCount is still not updated at this point)
Message is successfully sent, so becomes state == nil (original message's replyCount is now updated)

You should always use the latest values returned from the publisher.

**Comment by tokirin** [comment] 2022-03-08 01:24
@b-onc 
You should check all cases in that video.
It sometimes emits correct latest value, in case of that video, just case of 2 and 6 only emits correct value.
I want to receive correct reply count for all cases.

**Comment by tokirin** [comment] 2022-03-08 01:55
I print reply count for all of updates from delegate function using following code.

```Swift

  func channelController(_ channelController: ChatChannelController, didUpdateMessages changes: [StreamChat.ListChange<ChatMessage>]) {
    changes.forEach { change in
      switch(change) {
      case let .update(item, _):
        print("Message text \(item.text) replyCount \(item.replyCount)")
      default:
        return
      }
    }
    ...
  }
```
and you can check the result in [this video](http://gofile.me/4jHDt/HNQNwyCYM)
This time, It returns wrong values for all of cases 🥲

**Comment by polqf** [comment] 2022-03-11 10:15
Hi @tokirin,

What you are describing here seems to be a common misconception around `Publisher`s. 
Publisher uses willSet semantics, which means that the notification is fired before the value is actually changed.

You can read more about it in the following links. Those contain further explanations as well as workarounds: 
- https://forums.swift.org/t/is-this-a-bug-in-published/31292/24
- https://stackoverflow.com/questions/58403338/is-there-an-alternative-to-combines-published-that-signals-a-value-change-afte

**Comment by nuno-vieira** [comment] 2022-03-11 16:03
> Hi @tokirin,
> 
> What you are describing here seems to be a common misconception around `Publisher`s. Publisher uses willSet semantics, which means that the notification is fired before the value is actually changed.
> 
> You can read more about it in the following links. Those contain further explanations as well as workarounds:
> 
> * https://forums.swift.org/t/is-this-a-bug-in-published/31292/24
> * https://stackoverflow.com/questions/58403338/is-there-an-alternative-to-combines-published-that-signals-a-value-change-afte

@polqf Keep in mind, @tokirin also tried this with the delegate event and the behaviour is the same. 

@tokirin We are going to investigate the issue, we already have the feeling that it might be related to not increasing the reply count in the database, and relying only on the Network request to update the reply count. 

We will get back to you once we have more news 👍 

Best,
Nuno

**Comment by tokirin** [comment] 2022-03-15 02:24
Thanks to your devotion @nuno-vieira
I expected #1831 to solve this problem.
As it seems to be end game, I merged that branch to 4.11.0 release in our fork repo.
but it doesn't work to this problem 😢

**Comment by tokirin** [comment] 2022-03-16 09:18
@nuno-vieira We finally found WHAT CAUSES PROBLEM.

We succeeded to reproduce in StreamChat Sample App.
In our usecase, the all of reply has `quotedMessageId` and set `showReplyInChannel` true.
Without `quotedMessageId`, It works fine. but in opposite case, it happens.
We confirmed the message's `type` is changed to `regular` when `quotedMessageId` is set (originally it is `reply` without `quotedMessageId`) and suspect It affects.
Please check for this usecase

Thanks for your devotion.

**Comment by nuno-vieira** [comment] 2022-03-16 15:09
Hi @tokirin!

I still can't reproduce this with your scenario. I did find a UI bug, but it is not related to the LLC (StreamChat). If you disable this in our `DemoAppCoordinator.swift` file: 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/12814114/158619257-7ec96678-510e-4974-a55e-0d144b002b92.png">

And then run the demo app, this is the result:

https://user-images.githubusercontent.com/12814114/158619395-86abb7ce-cded-4501-bed9-e756c164da52.mov

**Comment by tokirin** [comment] 2022-03-16 16:22
@nuno-vieira when you reply, you have to quote original message for every reply in Sample App

**Comment by nuno-vieira** [comment] 2022-03-16 16:49
Hi @tokirin,

I think I was able to understand what you mean. This is the behaviour, right?

https://user-images.githubusercontent.com/12814114/158643205-b800dc22-673c-4e96-a937-296cbf6cd641.mov

Best,
Nuno

**Comment by polqf** [comment] 2022-04-25 11:56
Hi @tokirin & @EuyjaeHwang,

We've finally found the root cause of this issue. Our backend team is working on it at the moment and will let you know once fixed.

Thank you for your patience!

**Comment by EuyjaeHwang** [comment] 2022-04-27 05:19
It works fine!
Thanks 👍

**Closed** 2022-04-27 05:19 UTC
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), 📆 Planned
