### ISSUE TITLE
Message list scrolling issue while unpin messages 

### ISSUE THREAD

**Issue by jitendra-simform** [GetStream/stream-chat-swift#2111] opened 2022-06-21 13:37 UTC
## What did you do?
I have unpinned messages 

## What did you expect to happen?
Message list should not scroll on unpin messages

## What happened instead?
Message list start scrolling while unpin messages 

GetStream Chat version: 4.16.0
GetStream Chat frameworks: StreamChat, StreamChatUI
iOS version: iOS 15
Swift version: Swift 5
Xcode version: Xcode 13.1
Device: iPhone 13.1 Simulator

## Additional context
// facing issue in below PR as well 
// https://github.com/GetStream/stream-chat-swift/pull/2107

// Here is unpin message function 
    open func unPinMessage(message: ChatMessage, completion: ((Error?) -> Void)? = nil) {
        guard let cid = dataSource?.channel(for: self)?.cid else {
            return
        }
        let messageController = client.messageController(
            cid: cid,
            messageId: message.id
        )
        messageController.unpin(completion: { [weak self] error in
            completion?(error)
        })
    }

https://user-images.githubusercontent.com/97155807/174811077-2d27946f-12e8-4c40-9c33-d7f32d64c5e8.mov

thanks

**Comment by SSaleemSSI** [comment] 2022-06-27 07:52
> Hi,
> 
> this issue is a possible duplicate of #2094.
> 
> We're tracking this issue internally already.

Can you please resolve my issue? 
https://github.com/GetStream/stream-chat-swift/issues/2120

**Comment by nuno-vieira** [comment] 2022-07-05 18:19
Closing this one, since it is a duplicate of: https://github.com/GetStream/stream-chat-swift/issues/2094, we will track this issue on the 2094 issue, thank you!

**Closed by nuno-vieira** 2022-07-05 18:19 UTC
Labels: 🐞 Bug, 📆 Planned
