### ISSUE TITLE
Message Search Not Working 

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swift#3115] opened 2024-03-27 18:54 UTC
## What did you do?
I am trying to search message but it did not search the message from current user's channels. Suppose we search "appointment" word and we have message which contains that word but we are not getting any search result.

## What did you expect to happen?
When we search any thing then all messages should show which contains that message. 

As you can see we have the message which contain "appointment" text 
<img width="469" alt="Screenshot 2024-03-25 at 7 20 49 PM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/8b846167-657f-433a-9340-1c9338341af5">

But when we search that then no message is coming. 
<img width="474" alt="Screenshot 2024-03-25 at 7 22 00 PM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/a507a50c-2a0e-4060-92b1-6a6a3df26c2e">

## What happened instead?
No message show which contains "appointment" word etc. 

## GetStream Environment
**GetStream Chat version:** 4.44.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI 4.44.0
**iOS version:** IOS 15
**Swift version:** Swift 5+
**Xcode version:** 15.0.1
**Device:** IPhone 12 Pro Simulator

**Comment by nuno-vieira** [comment] 2024-03-28 13:47
Hi @Zee-93,

I'm not able to reproduce the issue in our DemoApp:

https://github.com/GetStream/stream-chat-swift/assets/12814114/e4cbfac5-bbcc-4740-9855-c2ee9d125cf5

Please ,update the SDK to the latest version. If you are still having issues, try to share any customization code or queries that you have.

Best,
Nuno

**Comment by Zee-93** [comment] 2024-03-28 18:21
@nuno-vieira  I am not customizing the query. I am using the default SDK search.

**Comment by nuno-vieira** [comment] 2024-03-28 19:15
@Zee-93 You can read more about how to configure search here: https://getstream.io/chat/docs/sdk/ios/uikit/components/channel-list/#search

**Comment by nuno-vieira** [comment] 2024-04-01 10:32
Hi @Zee-93,

We are closing this one for now. But if you still have doubts please let us know.

Best,
Nuno

**Comment by Zee-93** [comment] 2024-04-01 11:15
Hi Nuno Vieira,

I am preparing a demo for you in which you can see the issue related to
search. Apologies for the delayed response as i was looking into the github
link for the solutions.

Regards,
Zee

**Comment by Zee-93** [comment] 2024-04-02 09:41
Hi Nuno Vieira,

Please find the attached demo with the issue, i have also attached a video.
In this demo Search is not working. Like I have messages with “Application”
or “Proposal” text but did not get those messages. Please have a look into
that issue. That issue is very much frequent. Thanks.

Regards,
Zee

**Comment by nuno-vieira** [comment] 2024-04-02 09:44
Hi @Zee-93, which demo or video? I don't see anything

**Comment by Zee-93** [comment] 2024-04-02 10:10
I have attached those in my earlier email. Can you confirm if you received
them?

**Comment by Zee-93** [comment] 2024-04-02 10:17
https://github.com/GetStream/stream-chat-swift/assets/127435927/8f184a43-2e6a-458b-bd8d-8e24ee276845

**Comment by Zee-93** [comment] 2024-04-05 10:32
Hi Nuo,

Is there any update on this? Looking forward to hearing from you. Thanks

**Comment by Zee-93** [comment] 2024-04-08 08:11
@nuno-vieira  did you check the demo code where that issue is re-produced?

**Comment by nuno-vieira** [comment] 2024-04-08 16:50
Hello @Zee-93!

I was able to reproduce the issue with your app. This looks like it is a backend issue, not iOS related.

You should reach out to support in that case here: https://support.getstream.io/hc/en-us

Sorry for the inconvenience!

Best,
Nuno

**Closed by nuno-vieira** 2024-04-08 16:50 UTC
Labels: ❓ Question
