### ISSUE TITLE
currentUnreadCount on Channel object is always 0

### ISSUE THREAD

**Issue by alekseevpg** [GetStream/stream-chat-swift#119] opened 2020-03-16 12:15 UTC
## What did you do?
I'm trying to get a currentUnreadCount of a channel to update my custom channelList tableView
I've tried to directly init Channel with id, and request it through Client.shared.channels(query: query)

## What did you expect to happen?
Once i get Channel object currentUnreadCount property should return me non zero count if there are any unread messages.

## What happened instead?
Even if there are unread messages (which i can see if i'll subscribe to unreadCount driver) this property always return 0

## GetStream Environment
**GetStream Chat version:** 1.6.0
**iOS version:** 13.3
**Swift version:** 5.1.3
**Xcode version:** 11.3.1
**Device:** iPhone 8 Plus 13.3 simulator

**Comment by b-onc** [comment] 2020-03-18 17:04
Hello @alekseevpg 
`currentUnreadCount` works as expected in our Example project. You can see that we use it in `DarkChannelsViewController.swift:L106`.
Can you provide a sample project where this doesn't work?

**Comment by alekseevpg** [comment] 2020-03-18 18:25
It's super simple.
I did based on your example app. 
Login and press "CHECK CUSTOM CHANNELS VIEW" button

[Example.zip](https://github.com/GetStream/stream-chat-swift/files/4350660/Example.zip)

unreadCount is 0 for every channel, but if i switch to your darkmode then it's fine

**Comment by b-onc** [comment] 2020-03-19 10:22
Hello @alekseevpg ,
I'm not able to build the project you've sent.

**Comment by alekseevpg** [comment] 2020-03-19 16:06
Ok, let's try again. Now i'll attach full copy of your repo

[stream-chat-swift.zip](https://github.com/GetStream/stream-chat-swift/files/4355585/stream-chat-swift.zip)

**Comment by b-onc** [comment] 2020-03-20 13:40
Hello @alekseevpg ,

Thanks for the project. I can replicate the issue and also pinpointed the cause. You can expect this to be fixed in 2.0.

**Comment by alekseevpg** [comment] 2020-03-20 17:27
Hey @b-onc 

Cool thanks. Any ETA on 2.0?

I'm not quite get what do you mean by regular channel objects?

if i change the from the ChannelResponse to 

```
   var customChannels: [Channel] = []
            for response in responses {
              let customChannel = Channel(type: .messaging, id: response.channel.id)
              customChannels.append(customChannel)
              print(customChannel.currentUnreadCount)
            }
```

result will be the same, all currentUnreadCount are 0

**Comment by b-onc** [comment] 2020-03-23 10:21
@alekseevpg By "regular channel objects" I mean, in a `ChatViewController` you'll have `channelPresenter`, and it has a channel property `channelPresenter.channel`.
You can rely on `currentUnreadCount` being correct in that one.
2.0 is to be released this week, hopefully.

**Comment by b-onc** [comment] 2020-04-02 15:20
Hello @alekseevpg ,
This is fixed in our upcoming release 2.0. Make sure you're filtering for channels that the current user is a member of, and include the `option: [.state]` while querying.

**Closed by b-onc** 2020-04-02 15:20 UTC
Labels: backend, bug, core

**Comment by buh** [comment] 2020-04-02 15:24
Hi @alekseevpg 
There are changes in your example:

```swift
Client.shared.rx.queryChannels(filter: .currentUserInMembers & .equal("type", to: "messaging"), options: .state)
    .observeOn(MainScheduler.instance)
    .subscribe(onNext: { [weak self] (responses: [ChannelResponse]) in
        for response in responses {
            print(response.channel.unreadCount.messages)
        }
        
        let controller = CustomViewController(channels: responses.map { $0.channel })
        self?.navigationController?.pushViewController(controller, animated: false)
    })
    .disposed(by: disposeBag)
```

There is a result:
![image](https://user-images.githubusercontent.com/284922/78266670-61d7af00-7506-11ea-8bcd-805ad408a6b7.jpeg)

**Comment by alekseevpg** [comment] 2020-04-02 15:46
@buh hey, is it working in the latest release? no need to wait for 2.0.0?

**Comment by buh** [comment] 2020-04-02 15:47
We are releasing 2.0 just now.
My example based on 2.0, but you can try the same for 1.x.
