### ISSUE TITLE
Links Are Not Clickable

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swift#3266] opened 2024-06-25 15:17 UTC
## What did you do?
I have message into the chat with the link but links are not clickable. Stream chat sdk not validating some links. 

When I write following link then link is not clickable in chat.
https://app.dripjobs.com/customerportal/proposals?customerId=4016000640773a134be988469ea918

If I write the following link then the link is clickble. 
https://app.dripjobs.com/customerportal/proposals/proposal/6962048677cfe6a43522fe4f36b95a

You can see the screenshot 
<img width="438" alt="Screenshot 2024-06-25 at 10 16 43 AM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/4f3b87a1-a29d-4cdf-8516-085f1568a419">

## What did you expect to happen?
Every link should be clickable. 

## What happened instead?
Some links are not clickable.

## GetStream Environment
**GetStream Chat version:** 4.44.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI 4.44.0
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by nuno-vieira** [comment] 2024-06-25 15:50
Hello @Zee-93,

Please update to the latest SDK version. The issue is fixed on the latest releases.

Thank you,
Nuno Vieira

**Closed by nuno-vieira** 2024-06-25 15:50 UTC

**Comment by Zee-93** [comment] 2024-06-25 16:25
@nuno-vieira  I have updated sdk version to latest release 4.57.0, but getting same issue.
