### ISSUE TITLE
ChatChannelAvatarView is blurred

### ISSUE THREAD

**Issue by yuehengshi** [GetStream/stream-chat-swift#1693] opened 2021-12-15 20:45 UTC
## What did you do?
The avatar image sometimes is blurred, not clear

## What did you expect to happen?
Showing clear image

## GetStream Environment
**GetStream Chat version: 4.5.1
**GetStream Chat frameworks: StreamChat, StreamChatUI
**iOS version: 15
**Swift version: 5
**Xcode version: 13.1
**Device: iPad

## Additional context
![WechatIMG3](https://user-images.githubusercontent.com/36277457/146262333-c65c856d-1dd0-4e6b-a92c-15d81907de25.jpeg)

**Comment by nuno-vieira** [comment] 2021-12-17 15:33
Hi @yuehengshi ! This seems to be a duplicate of https://github.com/GetStream/stream-chat-swift/issues/1541. We still can't reproduce this issue. Can you analyse the response from the Channel List and check which codec is the images using? 

Thank you for the report!

**Comment by yuehengshi** [comment] 2021-12-17 18:15
> Hi @yuehengshi ! This seems to be a duplicate of #1541. We still can't reproduce this issue. Can you analyse the response from the Channel List and check which codec is the images using?
> 
> Thank you for the report!

Could you explain what the codec means? Is it the "Nuke" used in the StreamChatUI?

Btw, I would like to show you the view structure of my project. The app has several tabs, for the chat page, there is a container view where the chat channel view controller is embedded in. I have tried to move the chat page to the first tab, the avatar showed very well, whereas when I moved it to the last tab, the avatar would be blurred.
![chat avatar clear](https://user-images.githubusercontent.com/36277457/146589621-0500b22f-a62f-434e-aa0b-6cdd93d04647.jpeg)
![chat avatar blurred](https://user-images.githubusercontent.com/36277457/146589627-34b40337-e6b2-4059-b439-bc44d1b8007e.jpeg)

**Comment by yuehengshi** [comment] 2021-12-17 18:43
I just figured it out!
I was like, initiating the "ChatChannelListVC"  after fetching the auth token in a thread, then adding it to the container view.
What I'm doing now is to initiate it in the main thread and add it to the container view, which is working well!

**Comment by nuno-vieira** [comment] 2021-12-17 18:45
Glad you figured it out! 😃 Thank you! I'll close the issue, and link this to the other reported ticket to see if they can fix it in the same way 👍

**Closed by nuno-vieira** 2021-12-17 18:45 UTC
Labels: bug, duplicate
