### ISSUE TITLE
Constant The operation couldn't be completed. (Starscream.WSError error 1.

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#1782] opened 2022-02-04 17:52 UTC
## What did you do?
In the last few weeks we have been seeing a lot of issues with socket connections to stream, which pops up the Banner that we are getting WSError err 1 

Currently we are still using 2.6.9 (can't make the move to 4.X right now)
Pointed at the base (east)

from our Log of Stream Logger
```
12:48:44.004  ❌ 💔😡 Disconnected by error WebSocketProviderError(reason: "The operation couldn't be completed. (Starscream.WSError error 1.)", code: 1, providerType: StreamChatClient.StarscreamWebSocketProvider, providerError: Optional(Starscream.WSError(type: Starscream.ErrorType.securityError, message: "accept header doesn\'t match", code: 1))) in websocketDidDisconnect(error:)[304]
12:48:44.635  ❌ 💔😡 Disconnected by error WebSocketProviderError(reason: "The operation couldn't be completed. (Starscream.HTTPUpgradeError error 0.)", code: 0, providerType: StreamChatClient.StarscreamWebSocketProvider, providerError: Optional(Starscream.HTTPUpgradeError.notAnUpgrade(200))) in websocketDidDisconnect(error:)[304]
12:48:47.333  ❌ 💔😡 Disconnected by error WebSocketProviderError(reason: "The operation couldn't be completed. (Starscream.HTTPUpgradeError error 0.)", code: 0, providerType: StreamChatClient.StarscreamWebSocketProvider, providerError: Optional(Starscream.HTTPUpgradeError.notAnUpgrade(200))) in websocketDidDisconnect(error:)[304]
```

## GetStream Environment
**GetStream Chat version: 2.6.9
**GetStream Chat frameworks:** StreamChat,SteamChatCore
**iOS version: any
**Swift version: 5.5
**Xcode version:13.X
**Device: any ios

**Comment by khoogheem** [comment] 2022-02-09 16:27
Thanks -

Let me see if I can get logs.. 
But yes it looks like we do a two hour window on the `exp`

**Comment by b-onc** [comment] 2022-02-10 11:32
@khoogheem I don't think this is caused by expired tokens, but it might be related to it.

**Comment by bielikb** [comment] 2022-02-25 07:48
Hi @khoogheem,

Im just following here. Is the issue still occuring? Do you have any updates? Please let us know how we could help you

Also, we can help you to migrate to our latest version, once you'll be ready. Our v4+ is actively maintained and it's more likely any reported issues will be resolved within feasible timeframe.

Thanks for understanding.

Best,
Boris Bielik

**Comment by adamrushy** [comment] 2022-03-11 10:26
Closing the issue as looks to be resolved.

**Closed by adamrushy** 2022-03-11 10:26 UTC
Labels: help wanted, sdk:StreamChat(v2)
