### ISSUE TITLE
Problems loading channels

### ISSUE THREAD

**Issue by sasojadrovski** [GetStream/stream-chat-swift#2548] opened 2023-03-27 19:53 UTC
## What did you do?
I am trying to load the channels using a `ChatChannelListController`.

## What did you expect to happen?
The channels should be loaded successfully.

## What happened instead?
The UI gets frozen, and no channels are loaded.

## GetStream Environment
**GetStream Chat version:** 4.29.0
**GetStream Chat frameworks:** StreamChat
**iOS version:** 16.3.1
**Swift version:** 5.7
**Xcode version:** 14.2
**Device:** iPhone 14 Pro

## Additional context
Upon opening a screen in the app, I am creating a `ChatChannelListController` using the following code:
```swift
// 1. Create the channel list controller
let channelListController = makeChannelListController()
// 2. Load the (cached) channels 
let conversations = channelListController.channels
// 3. Setup subscriptions
channelListController?.channelsChangesPublisher.sink { 
  // Handle the stream of changes appropriately 
} 
// 4. Synchronize the channels
channelListController.synchronize { error in 
  // Refresh the channels, handle errors, etc.
}
. . . 
  
func makeChannelListController(filter channelsFilter: ChannelsFilter? = nil) -> ChatChannelListController? {
  guard let client = client else {
    logClientNotInstantiated(from: #function)
    return nil
  }
  guard let currentUserId = client.currentUserId else { return nil }
  var filters: [Filter<ChannelListFilterScope>] = [
    .equal(.type, to: .messaging),
    .containMembers(userIds: [currentUserId])
  ]
  switch channelsFilter {
  case .directMessaging:
    filters.append(.equal(.memberCount, to: 2))
  case .groupMessaging:
    filters.append(.greater(.memberCount, than: 2))
  case .none:
    break
  }
  return client.channelListController(query: .init(filter: .and(filters)))
}
```
However, sometimes, after using the app and chatting with multiple people, the channels do not load and the closure of the `synchronize` method is never invoked. It seems like the `APIClient`s request operation never finishes, and the `completion` callback is never invoked.

Could you please take a look and let me know if anything seems odd with the code snippet I provided? If not, could you please investigate this further?

Please let me know if you need additional details.

Thanks in advance!

Best regards,
Sasho

**Comment by alteral** [comment] 2023-03-28 11:18
Hi @sasojadrovski,

Thank you for the report. We are investigating this and will get back to you soon.

Best,
Alexey

**Comment by alteral** [comment] 2023-03-28 11:21
In the meantime, @sasojadrovski, if you could share a video that reproduces the issue, it would be very helpful. Thanks!

**Comment by nuno-vieira** [comment] 2023-03-28 15:17
@sasojadrovski Also, are you calling this from the main thread or a background thread?

**Comment by sasojadrovski** [comment] 2023-03-30 22:28
Hi @alteral and @nuno-vieira,

Thank you both for your prompt reply!

@alteral I am attaching a video of the Messages screen not being able to load the messages. Unfortunately, this time the app did not freeze, but the messages did not load anyway. It might be worth mentioning that so far we have been able to only reproduce this issue on one of our test devices, for one user account. Additionally, we have noticed that completely removing the app and re-installing it, resolves it for some time, but after using the chat system for a while, the issue reappears, which makes us think that it might be related to the SDK's caching (storage) mechanism, or a failure retrieving the channels from the API. Either way, when we debugged the issue, the `synchronize` method's completion closure was never invoked, and it seemed like the request operation of the `APIClient` never resolved.

Unfortunately we don't have SDK logs at this point, as the issue was noticed on a production build, as it was about to be pushed to Apple for a review.  

@nuno-vieira Yes, we are calling this from the main thread.

https://user-images.githubusercontent.com/12610025/228977595-a54e8d1c-9216-4762-a97e-5efd16c24b9e.mp4

**Comment by nuno-vieira** [comment] 2023-03-31 14:30
Hi @sasojadrovski,

The SDK logs will be very helpful here. Let us know when you have them. There is currently an issue on the backend that makes the channel list parsing fail in rare situations.  This is currently being fixed by the backend, but the 4.30.0 release on iOS makes this more resilient, and it won't completely fail the channel list request. So we recommend also updating to 4.30.0.

Either way, we will need more data from you to be 100% sure this is the same issue we are talking about. 

Best,
Nuno

**Comment by alteral** [comment] 2023-03-31 14:37
Hi @sasojadrovski,

Thanks for sharing the video! As @nuno-vieira just mentioned, we need more data, and the SDK logs would be the best option. As an additional question, have you tried sniffing the traffic (e.g. using Proxyman)? Is there anything suspicious? 

Best,
Alexey

**Comment by sasojadrovski** [comment] 2023-04-04 22:08
Hi @nuno-vieira, @alteral,

Thank you both for replying. We have managed to collect logs from the device of the affected user. We used the `.debug` log level. I am attaching the logs here.

@alteral No, we haven't sniffed the traffic.

Looking forward to hearing from you.

Best regards,
Sasho

[stream-logs.txt](https://github.com/GetStream/stream-chat-swift/files/11153622/stream-logs.txt)

**Comment by alteral** [comment] 2023-04-05 12:07
Hi @sasojadrovski,

Thanks for sharing the logs. Unfortunately, I don’t see anything useful or suspicious there, apart from, as you said, the `synchronize` has never been called.

Can I ask where/how you are keeping this `channelListController` instance? Could it be that it gets deallocated? Also, as much integration code you can give, the better.

Best,
Alexey

**Comment by aaceti** [comment] 2023-04-08 18:30
Hi @nuno-vieira and @alteral,

Thank you for your help in trying to get this resolved. I am the owner of the Clic App and we made the decision to integrate stream into our social app. Unfortunately, we have been facing several issues with the SDK throughout the past few months and while we are hoping to maintain a long term relationship with Stream, we can't continue to face these issues if we are going to stick with the platform.

As a result of the issues that have an occurred with Stream, our investors are getting extremely frustrated and we have had several delays in our launch. We can't delay any further, this is costing us money and making it slower to go to market with the launch of our new brand. Furthermore, our users are experiencing issues with the chat which is the core functionality of our app leading to lower retention and engagement. 

We really do want to stay with the Stream platform long term so would it be possible for someone to jump on a quick call and screen share with @sasojadrovski and myself in order to review our code and determine why we are having issues?

**Comment by nuno-vieira** [comment] 2023-04-10 11:59
Hi @aaceti,

In order to fix the issue, we need to be able to reproduce the issue. But in this case, it looks like it is an integration issue since we do not have any other customer reporting this. So, it is critical that you share as much integration code as possible. If you don't want to share the code publicly, you can reach out to our support team here: https://getstream.io/contact/support/, and we will take it from there.

I'm sorry, but we are only offering integration calls for our enterprise customers at the moment.

Best,
Nuno

**Comment by sasojadrovski** [comment] 2023-04-11 20:27
Hi @testableapple, @nuno-vieira,

The `ChatChannelListController`' instance is not deallocated and is kept in a `ViewModel`. I am sharing as much as I can from our code for the Messages screen.

```swift
import Combine
import Foundation
import PromiseKit
import StreamChat

final class MessagesViewModel {

  // MARK: Public Properties
  
  var refreshConversations: AnyPublisher<Void, Never> { _refreshConversations.eraseToAnyPublisher() }

  // MARK: Private Properties

  private let chatService: ChatEngine
  private var subscriptions = Set<AnyCancellable>()
  private var userLoggedOutSubscription: AnyCancellable?
  private var channelListController: ChatChannelListController?
  private lazy var conversations = [Conversation]()

  // MARK: Initialization

  init(chatService: ChatEngine = ChatService.shared) {
    self.chatService = chatService

    userLoggedOutSubscription = chatService
      .userLoggedOutPublisher
      .sink { [weak self] in
        self?.subscriptions.forEach { $0.cancel() }
        self?.subscriptions.removeAll()
      }
  }
}

// MARK: - ViewControllerLifecycleObservable

extension MessagesViewModel: ViewControllerLifecycleObservable {

  func viewControllerTransitioned(to state: ViewControllerState) {
    switch state {
    case .viewDidLoad:
      channelListController = chatService.makeChannelListController()
      loadConversations()
    case .viewWillAppear:
      channelListController = chatService.makeChannelListController()
    default:
      break
    }
  }
}

// MARK: - Private Methods

private extension MessagesViewModel {

  func loadConversations() {
    guard let channelListController = channelListController else { return }
    conversations = channelListController.channels.filter { $0.membership != nil }.map(Conversation.init)
    setupChannelListControllerSubscriptions()
    synchronizeChannelListController()
  }

  func setupChannelListControllerSubscriptions() {
    channelListController?
      .channelsChangesPublisher
      .receive(on: DispatchQueue.main)
      .sink { [weak self] changes in
        guard let self = self else { return }
        for change in changes {
          switch change {
          case let .insert(channel, indexPath):
            if indexPath.item <= self.conversations.count {
              self.conversations.insert(Conversation(from: channel), at: indexPath.item)
            } else {
              self.conversations.append(Conversation(from: channel))
            }
          case let .move(_, fromIndex, toIndex):
            self.conversations.move(fromOffsets: IndexSet(integer: fromIndex.item), toOffset: toIndex.item)
          case let .update(channel, indexPath):
            if channel.membership == nil {
              if let channelIndex = self.conversations.firstIndex(where: { $0.cid == channel.cid }) {
                self.conversations.remove(at: channelIndex)
              }
            } else {
              if let channelIndex = self.conversations.firstIndex(where: { $0.cid == channel.cid }) {
                self.conversations.remove(at: channelIndex)
                self.conversations.insert(Conversation(from: channel), at: channelIndex)
              } else {
                if indexPath.item <= self.conversations.count {
                  self.conversations.insert(Conversation(from: channel), at: indexPath.item)
                } else {
                  self.conversations.append(Conversation(from: channel))
                }
              }
            }
          case let .remove(channel, _):
            if let channelIndex = self.conversations.firstIndex(where: { $0.cid == channel.cid }) {
              self.conversations.remove(at: channelIndex)
            }
          }
        }
        self._refreshConversations.send()
      }
      .store(in: &subscriptions)
  }

  func synchronizeChannelListController() {
    guard let channelListController = channelListController else { return }
    firstly {
      channelListController.synchronize()
    }.ensure {
      self._refreshConversations.send()
    }.catch { error in
      Messenger.notify(
        .error,
        title: "Error fetching conversations",
        description: error.localizedDescription
      )
    }
  }
}
```

Thank you both for looking into this!

Best regards,
Sasho

**Comment by nuno-vieira** [comment] 2023-04-17 16:53
Hi @sasojadrovski!

What is this part of the code doing? 

```swift
func synchronizeChannelListController() {
    guard let channelListController = channelListController else { return }
    firstly {
      channelListController.synchronize()
    }.ensure {
      self._refreshConversations.send()
    }.catch { error in
      Messenger.notify(
        .error,
        title: "Error fetching conversations",
        description: error.localizedDescription
      )
    }
  }
```

What does `firstly` do?

Another question I have is, you mention that the UI freezes, right? This mean a Thread is blocked. When you click "pause" in the debugger, which thread is blocked, and can you see who is responsible for that?

<img width="423" alt="image" src="https://user-images.githubusercontent.com/12814114/232556049-b57d4037-f447-4549-8634-6ec564a3f5a1.png">

Best,
Nuno

**Comment by aaceti** [comment] 2023-04-17 18:08
Hi @nuno-vieira,

While we are waiting for @sasojadrovski to respond, I thought I'd let you know the behaviour of the issue to maybe help solve the problem.

When the app is installed and I log in the chat works fine for maybe 2-3 days (sometimes sooner). It then stops working and freezes once you tap to access the chat section of the app. After a few days, the app stops freezing and allows the chat screen to appear but shows a loading wheel that never goes away. If I were to delete the app and reinstall and login, it would go through this same process again.

**Comment by nuno-vieira** [comment] 2023-04-18 11:15
Hi @sasojadrovski!

This piece of code looks to be the root cause of the issue: 
```swift
func viewControllerTransitioned(to state: ViewControllerState) {
    switch state {
    case .viewDidLoad:
      channelListController = chatService.makeChannelListController()
      loadConversations()
    case .viewWillAppear:
      channelListController = chatService.makeChannelListController()
    default:
      break
    }
  }
```

When the view loads, you create the controller and then load the conversations. But right after, on the `viewWillAppear`, you replace the channel list controller and don't call `loadConversations()` again. Most likely, the issue is here. Because this is happening:
1. View loads -> Channel List Controller is created, and you call `synchronize().` 
2. View appears -> New Channel List Controller is created, and the previous one is discarded, so the completion of the first sync will never be called.

You only need to create the channelListController on viewDidLoad. You shouldn't need to create it whenever the view appears.

We believe this is the actual issue. So, for now, we will close the issue, but feel free to re-open it if, after these changes, you still have problems.

Best,
Nuno

**Closed by nuno-vieira** 2023-04-18 11:15 UTC
Labels: 🔎 Investigating

**Comment by sasojadrovski** [comment] 2023-05-02 21:17
Hi @nuno-vieira,

Apologies for the delayed response, and thank you once again for getting back to us.

> What is this part of the code doing?
That part of the code is simply calling synchronize on the ChatChannelListController and makes sure to catch any errors that might pop up, and it refreshes the UI regardless of the outcome of the `synchronize` call.
The same code could be written without the use of `PromiseKit` like this:
```swift
func synchronizeChannelListController() {
  guard let channelListController = channelListController else { return }
  channelListController.synchronize { [weak self] error in
    if let error = error {
      Messenger.notify(
        .error,
        title: "Error fetching conversations",
        description: error.localizedDescription
      )
    } else {
      self?._refreshConversations.send()
    }
  }
}
```

> What does firstly do?
`firstly` is just a syntactic sugar from PromiseKit that marks the start of a promise chain. 

> This piece of code looks to be the root cause of the issue:
Yes, I agree that that specific part of the code does not look nice, however there's a reason why it was written like that.

Our Messages screen is consist of three tabs (imagine a UIPageViewController with 3 pages). The first and second tab are related to the channels (messages/conversations). The first one displays all channels (chats), regardless if they are 1:1 or group chats. The second only displays the group chats. 

Since we were unable to find (in your documentation) a nice way to change the Filter of an already instantiated `ChatChannelListController`, whenever the user switches between the Messages and Groups tabs, we decided to re-create the `ChatChannelListController` when the view appears. If we did not do that, then (since the `ChatClient` is a singleton), our `ChatChannelListController`'s filter would be set to the one that was last instantiated (e.g. the one responsible for the groups) — Please let us know if there's a better way to achieve this behavior without manually filtering the channels for 1:1/groups.

Regardless, we commented out that part of the code, leaving only the part in `viewDidLoad` and unfortunately it did not resolve the issue for us.

Looking forward to hearing from you.

Best regards,
Sasho

**Comment by nuno-vieira** [comment] 2023-05-05 14:58
Hi @sasojadrovski!

Although `ChatClient.shared` is a singleton, whenever you call `ChatClient.shared.channelListController()`, it always creates a new instance of `ChatChannelListController`. We are actually planning on changing the function calls to have a `make` prefix to be more clear that this is a factory method.

So, in order for your code to work, you need to call synchronize in `viewWillAppear()` too. Right now you are only calling synchronize in the viewDidLoad method, in an instance which will be replaced by `viewWillAppear()`. 

This is the change you need to make:
```swift
func viewControllerTransitioned(to state: ViewControllerState) {
    switch state {
    case .viewDidLoad:
      channelListController = chatService.makeChannelListController()
      loadConversations()
    case .viewWillAppear:
      channelListController = chatService.makeChannelListController()
      loadConversations() <---- Make sure to call synchronize in viewWillAppear. 
    default:
      break
    }
  }
```

Best,
Nuno
