### ISSUE TITLE
Not able to send video and image both at same time 

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-swift#842] opened 2021-02-24 07:41 UTC
when any user upload video and image file both same time in version 2.6.4 then image sent successfully but Video not sent.

**Comment by JeremPlln** [comment] 2021-03-02 09:14
I have a similar issue but with an image only. If I upload an image and send it, it doesn't appear in the chat. I have to dismiss the view and show the view again to see my image. It also happens when I join a text message with the image.

sum up :
image + text message = nothing appears on screen
image only = nothing appears on screen

**Comment by iosiappmemes** [comment] 2021-03-02 09:20
Hi @JeremPlln 

even after 4 days  of posting issue, i m waiting for response from stream Team.

It seems they they no time for reply and resolve the issue.

**Comment by VojtaStavik** [comment] 2021-03-02 09:33
Hi 👋 @iosiappmemes @JeremPlln, sorry for the seeming inactivity in this issue. We're investigating it and will post the update here shortly. Thank you for your patience.

**Comment by iosiappmemes** [comment] 2021-03-02 09:43
Hi @VojtaStavik 

Thank you. will wait for update.

**Comment by JeremPlln** [comment] 2021-03-02 11:21
Thank you @VojtaStavik ! Here is a video of the problem :) 

Uploading Image d’iOS (2).MP4…

**Comment by b-onc** [comment] 2021-05-12 13:32
Hello @iosiappmemes 
The issue of not being able to send images and files at the same time were resolved in commit 17fc2c6e53bec43be35c2a8364f8a5c5abb597b9 and will be released in 2.6.7.

@JeremPlln , thanks for the video! I cannot reproduce the issue. Can you enable and share the logs for this session?

**Comment by b-onc** [comment] 2021-05-18 12:06
Hello @iosiappmemes 
The issue was fixed in 2.6.7

@JeremPlln , if you're still seeing the issue, please open a new ticket with logs, thank you!

**Closed by b-onc** 2021-05-18 12:06 UTC
Labels: bug, sdk:StreamChat(v2), upcoming
