### ISSUE TITLE
Push notifications when iOS client is in foreground

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#694] opened 2020-12-23 22:41 UTC
## What are you trying to achieve?
We'd expect our users to receive push notification about a new message even when app is in foreground

## What would be the better way?
Implementation would be possible by one of two ways:
- implementing local push to work while in foreground (avoid `if background` check)
- sending remote notifications even when user is connected, but then not showing them when client is in foreground when that's configured so in the config

gz#8231

**Comment by b-onc** [comment] 2021-01-12 13:38
Duplicate of #711

**Closed by b-onc** 2021-01-12 13:38 UTC
