### ISSUE TITLE
Can't create channel after reconnecting to the network

### ISSUE THREAD

**Issue by koron4ik** [GetStream/stream-chat-swift#413] opened 2020-08-19 20:41 UTC
## What did you do?
1) set user
2) turn off Wi-Fi. Socket disconnected
3) turn on Wi-Fi
4) create channel
5) I am getting .emptyConnectionId error. Seems like the socket cannot connect again after disconnecting.

If I call set(user:) the result never comes.

## What did you expect to happen?
Create channel

## What happened instead?
Error - "Web Socket connection id is empty. Authorization missed. Please call set(user:) and wait for its completion."

## GetStream Environment
**GetStream Chat version: 2.2.8
**GetStream Chat frameworks:** StreamChatClient
**iOS version: 13.6
**Swift version: 5
**Xcode version: 11.6
**Device: iPhone 11 (Simulator)

gz#5426

**Comment by b-onc** [comment] 2020-09-08 11:47
Fixed by #471

**Comment by b-onc** [comment] 2020-09-09 11:19
False-positive up there ⬆️ Issue might be still present on v2 (the PR was for v3), needs investigation

**Comment by cardoso** [comment] 2020-11-27 19:16
@b-onc I followed the steps with v2 in the sample app. Couldn't reproduce. @koron4ik are you still having this issue? If so, could you provide some code snippet or Xcode project that reproduces it? Thanks a lot.

**Comment by cardoso** [comment] 2020-12-01 14:59
Closing this one for now. @koron4ik I'll re-open if you tell us you're still having the issue.

**Closed by cardoso** 2020-12-01 14:59 UTC
