### ISSUE TITLE
ChatChannelVC misses messages if NSE processes a push with ChatRemoteNotificationHandler (with local storage on)

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swift#1827] opened 2022-03-07 05:44 UTC
## What did you do?
The bug:
- Open app. Navigate to a thread view. Background the app.
- Send a message. Receive a push. NSE processes the app with ChatRemoteNotificationHandler.
- Open the app. Notice that the new message never shows up in the thread view. <=== BUG
- go back to thread list view. enter the thread view again. This time you see the new message

Note that two conditions need to be met if you want to reproduce this bug:
- ChatClientConfig.isLocalStorageEnabled needs to be set to true for both main app and the NSE
- ChatClientConfig.applicationGroupIdentifier needs to be properly configured so that both NSE and main app share persistence.

## What did you expect to happen?
The new message should show up in thread view

## What happened instead?
The new message never shows up in thread view, even though you can receive newer messages and send messages in the thread view. The pushed message is just missing (unless you navigate away and come back to the same thread view)

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15
**Swift version:**
**Xcode version:**
**Device:** iPhone 13 Pro

## Additional context

Here is what I can gather (and I could be wrong).

Stream's persistence layer appears to use CoreData. The ChannelView listens to CoreData, gets a callback when updates happen, and update the view. This happens when everything happens in the same process ...

Now when a push comes in, ChatRemoteNotificationHandler in the NSE, a separate process, fetches the message and persists it to CoreData; but when the main app is running at the same time, the changes aren't communicated inter-process! So the view stays stale.

This is not the end. If you call channelController.synchronize on foreground, you'd think the view would update? Nope ... .synchronize kicks off a network request, which feeds the new message to CoreData. CoreData looks at it and says: I already have it! So no update notification is sent to the ChannelView, and the view stays stale ...

Now if you go back to ChannelListView and come back to ChannelView, it would kick off a fresh read of CoreData, at which point the new message shows up. Hmm ...

There are two options:
- Stream takes the stance that NSE should not share CoreData with the main app.
- Stream builds a solution (e.g. NSE tells main app something is happening, and the main app calls CoreData's refreshObjects or something to update stale views)

I don't know what you guys want to do, but this bug definitely got me and took me a while to figure out. I wouldn't wish this upon anyone else.

**Comment by nuno-vieira** [comment] 2022-03-07 22:30
Hi @linhewinner !

Thank you for all the details on the issue 👍 We will investigate this one and will update you as soon as possible. 

Keep in mind, we do not recommend using the local storage enabled in production (hence why it is disabled by default right now). We are almost finishing a major refactoring on the Offline Support, which should come out really soon, and this will change then, it will be enabled by default and it will be recommended to use in production.

Best,
Nuno

**Comment by linhewinner** [comment] 2022-03-17 23:22
Just tested with 4.12.0 (which has the refactored offline support).

This bug still repros, for the same root cause.

**Comment by b-onc** [comment] 2022-06-10 15:08
Internally tracked at CIS-1634

@linhewinner I've implemented the fix, PR will come next week

**Comment by nuno-vieira** [comment] 2022-07-13 16:37
Hi @linhewinner,

What is your use case to have the `isLocalStorageEnabled` to `true` in the NSE? Did you unblock this issue on your side by setting it to false? 

Best,
Nuno

**Comment by linhewinner** [comment] 2022-07-13 17:06
When NSE processed an incoming notification, I want it to insert the fetched data into local persistence, so that when the user opens the app from the push notif, they'd immediately see the message in UI.

If isLocalStorageEnabled is set to false in the NSE, the fetched message won't be persisted. The user taps on push, opens app and would have to wait for a couple of seconds for the message to arrive. It creates a jarring experience.

re: did you unblock this
I am setting isLocalStorageEnabled=false now, but the user experience sucks (as I described above).
I am hoping that I can re-enable isLocalStorageEnabled and improve the UX

**Comment by nicol3a** [comment] 2022-07-14 21:55
We're experiencing the same issue, even with the latest version (4.18.0).

**Steps to reproduce:**
1. Open the chat (sending and receiving messages works fine)
2. Put the app in the background
3. Wait for the following logs
```
...
[appDidEnterBackground()] > Background task -> ❌
....
[ConnectionRecoveryHandler.swift:216] [canReconnectAutomatically] > Reconnection is not possible (app 💤)
...
```
4. Send a message from the other user in the chat
5. The push notification is received
6. Open the app

**Observed result:**
The message received while the app was in the background never appear in the chat.

**Expected result:**
The message received while the app was in the background should appear in the chat.

As @linhewinner said, if the `isLocalStorageEnabled` is set to `false`, tapping the push notification does insert the message received into the chat, but only in that case.

Our clients are complaining that they have to kill and restart the app. Would be really cool to fix this asap.

Thanks!

**Comment by nuno-vieira** [comment] 2022-07-15 11:09
Hi @linhewinner @nicol3a!

The issue is fixed on the `develop` branch already and will be out on the next release.

We will let you know once the release is published. The ETA is next week.

Thank you for your patience!

Best,
Nunk

**Comment by nicol3a** [comment] 2022-07-15 13:17
Amazing! Just tested on `develop`, and it fixes my issue. Big thank you! 🙏

**Comment by linhewinner** [comment] 2022-07-15 17:07
Amazing. Out of curiosity, how did you fix this?

**Comment by nuno-vieira** [comment] 2022-07-21 15:10
> Amazing. Out of curiosity, how did you fix this?

You can see here how we fixed it: https://github.com/GetStream/stream-chat-swift/issues/1827#:~:text=%5BCIS%2D1634%5D%20Fix%20Channel%20missing%20messages%20from%20NSE%20push%20updates%20%232166

But basically, on the ChannelVC, we observer when the app comes to foreground again, and in that case we reset the FRC observers by setting the message list delegates and dataSource again.

**Comment by polqf** [comment] 2022-07-22 11:09
[4.19.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.19.0) is out, which contains the fix for this issue.
We are closing it for now, let us know if you need anything else 😄

**Closed by polqf** 2022-07-22 11:09 UTC
Labels: 🐞 Bug, 🎨 SDK: StreamChatUI, 🔜 Upcoming
