### ISSUE TITLE
Shut off Local Notifications

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#170] opened 2020-04-10 19:30 UTC
## What are you trying to achieve?

Currently in our Dashboard we do not have Notifications turned on.. so I would expect that this setting would be used as well for LocalNotifications, but it looks like that is not the case

What is the best way to go about turning off the ability to send the local notifications.

Also - This is probably a Bug but the notifications looked something like this:
**User Name @ UUID**

Bob B @ xxxxxx-xxxx-xxxx-xxxx
Hello??

**Comment by buh** [comment] 2020-04-10 19:34
Hi @khoogheem
If you switched off the `stayConnectedInBackground` for the client in his config the local notification won't work.

**Comment by khoogheem** [comment] 2020-04-10 19:42
Seems that that would work.. but then if you come back you take a slight hit of the UI to gather up all the new messages right?

I guess IMHO the LocalNotifications should have its own config or Adhere to what the Dashboard says.. No Pushes..  

But still give the benefit of getting messages in the background

**Comment by buh** [comment] 2020-04-10 19:50
`stayConnectedInBackground` was added to avoid reconnection when the app will return from the background. Unfortunately at this moment, we don't have the dashboard state for push notifications. But can definitely add a flag for local notifications.

**Comment by khoogheem** [comment] 2020-04-10 19:56
Ultimately I would like to have the ability to control Local Notifications without having to compromise the `stayConnectedInBackground` purpose

**Comment by koishi** [comment] 2020-04-28 17:27
@buh 
hi
I also want to disable local notifications.

However, stayConnectedInBackground seems to work better when the number of unread chats is retrieved by leaving it ON.

Are there any plans to add an option to disable local notifications?

**Comment by wasauce** [comment] 2020-06-01 04:16
@buh 

We also would like to disable local notifications. We consider this a bug as it is unintended behavior from our point of view.

**Comment by koishi** [comment] 2020-06-01 04:33
@wasauce 
I think this will work PR are merged 😄 
https://github.com/GetStream/stream-chat-swift/pull/290

**Closed** 2020-06-02 14:36 UTC
Labels: enhancement
