### ISSUE TITLE
Fix unsuccessful for issue 2200 (improve consistency when retrieving message after push notification) 

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swift#2220] opened 2022-08-06 18:21 UTC
## What did you do?
We are still seeing messages fail to appear sporadically in the channel when a user enters from a notification. This is a huge problem for us and is holding up our next release. Please help us get this resolved asap. 

## What did you expect to happen?
All messages should appear in the channel without fail

## What happened instead?
Intermittently, messages do not show in the thread 

## GetStream Environment
**GetStream Chat version:** 0.4.20
**iOS version:** 15.5
**Swift version:**
**Xcode version:**
**Device:** iPhone 11

**Comment by hugobernalstream** [comment] 2022-08-08 19:03
Hi @jfru,

Thanks for reaching out. Are you noticing any specific pattern when this is happening? if you notice one, please share steps to reproduce or more related info with us so we can investigate further. We will also continue analyzing internally.

Regards,
Hugo

**Comment by jfru** [comment] 2022-08-08 21:17
Thanks @hugobernalstream, much appreciated. I'm completely stumped about the specific repro steps. So far, I've only seen it happen in one channel. It's always the same channel and at this point 3 of the members in the channel have experienced the issue at different times.

**Comment by polqf** [comment] 2022-08-23 16:33
Hi @jfru,

We've been testing this, and we've been unable to reproduce it after 4.20.0.
Could you please send us a mail with the app id and the channel id to pol.quintana@getstream.com ?

**Comment by polqf** [comment] 2022-08-29 09:43
We're going to close it for now. Please reopen it if you are still having issues.

**Closed by polqf** 2022-08-29 09:43 UTC
Labels: 🐞 Bug, 🔎 Investigating

**Comment by saidReclip** [comment] 2022-09-19 10:12
Hi @polqf 
Seems like this issue still actual. 
Seems this only happen when accessing a chat from notification received. 
Also messages appear after user tap one of the left over notifications. 

GetStream Chat revision: "9a30f9212cc2a4ecf9f93cf0065239e6fc49d1cf"

**Comment by polqf** [comment] 2022-09-19 10:15
Hi @saidReclip ,
Are you sure there is no connectivity issues on your side while testing? Could you please share a video?

**Comment by jfru** [comment] 2022-09-19 20:38
I'm trying to repro this, but having a hard time. I don't think it was connectivity. I was using my phone and receiving message notification banners at the top of my phone. I tapped one and it entered the thread, but the messages weren't there. A few minutes later I tapped one of the remaining notifications in my notification center, which took me into the thread where about 7 or 8 missing messages from the other user in the chat all appeared at once

**Comment by polqf** [comment] 2022-09-20 00:09
Hi @jfru, bear in mind that we perform an API call once the Push Notification is received to get the updates. There are several things outside our control that can affect this process. Connectivity, Low Power mode and so on.

**Comment by jfru** [comment] 2022-09-20 02:14
For sure. I'm doubtful it was any of these in this instance. I had full battery and I was connected to my wifi with good connection. I was using the internet for other things at the same time as this happened, but I understand that it's hard for you to pursue with limited info. I'll keep an eye on it.
