### ISSUE TITLE
Crash when archive with Xcode 13

### ISSUE THREAD

**Issue by vankien96** [GetStream/stream-chat-swift#1478] opened 2021-09-25 04:09 UTC
## What did you do?
I got an issue when using Xcode 13 to upload build to TestFlight, It crashed when switching to the ChatChannelListVC tab.
I tried using Xcode 12 to archive and everything works fine.

## What did you expect to happen?
Not crash when ChatChannelListVC appear

## What happened instead?
Crash

## GetStream Environment
**GetStream Chat version: 4.0.1**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version: 15.0**
**Swift version: 5.5**
**Xcode version: 13.0**
**Device: iPhone 7 plus**

## Additional context
That is crash log:
![image](https://user-images.githubusercontent.com/26648523/134757367-2f4dafad-f1ee-4c9e-94ba-5bcb20ea12b2.png)

**Comment by tbarbugli** [comment] 2021-09-27 08:59
Thank you for reporting this, just a couple questions to speed things up:

- Do you use a custom Appearance object? If yes can you share that?
- Can you reproduce this locally?
- Is it possible to share the line numbers from the stack trace?

**Comment by vankien96** [comment] 2021-09-29 06:34
Do you use a custom Appearance object? If yes can you share that?
=> Yes, I custom the headerView like this:
```
        let titleView = UILabel()
        titleView.isUserInteractionEnabled = true
        
        titleView.text = Strings.Tabbar.chat
        navigationController?.navigationBar.topItem?.titleView = titleView
        let gesture1 = UITapGestureRecognizer(target: self, action: #selector(self.openSetting))
        titleView.addGestureRecognizer(gesture1)
        
        titleView.font = AppFont.boldFont.withSize(titleView.font.pointSize)
        titleView.sizeToFit()
```

Can you reproduce this locally?
=> No, it works well when I run directly with Xcode 13. But when archive to TestFlight => It crashes.
Archive with Xcode 12. it works ok.

Is it possible to share the line numbers from the stack trace?
=> The image above is all I got from the TestFlight crash report.

**Comment by adamrushy** [comment] 2021-10-04 14:27
Hey, @vankien96 I have raised a PR;
https://github.com/GetStream/stream-chat-swift/pull/1502

This should hopefully stop the app from crashing. We are now safely loading images from the bundle. I suggest building your app against this branch or `main` when we merge it to check the crash is now fixed.

**Comment by vankien96** [comment] 2021-10-04 15:37
Hi @adamrushy, I checked your branch and it fixed the crash. but now it cannot load icons, I saw your PR, it is problems with loading icons from the bundle.
It works well when run from Xcode. Do I need any config when archiving with Xcode 13?
![IMG_0056](https://user-images.githubusercontent.com/26648523/135880445-3ba41c07-ac51-4adb-9e17-0ae704d871cb.jpg)

**Comment by adamrushy** [comment] 2021-10-04 15:46
@vankien96 thanks for checking and glad the crash has gone. Are you able to share the full project with us? If it's private you can email me (adam.rush@getstream.io) or you can upload a sample here directly?

**Comment by vankien96** [comment] 2021-10-05 08:31
@adamrushy Our project is a large project so I cannot share it, let me try to create an example and send it to you.

**Comment by adamrushy** [comment] 2021-10-06 13:01
Hey, @vankien96 how are you getting on sharing the sample code? 💯

**Comment by vankien96** [comment] 2021-10-06 14:38
@adamrushy i sent the sample to your email, please help me check it.

**Comment by adamrushy** [comment] 2021-10-06 15:31
Thank you @vladpre92 it could well be CocoaPods specifically, I will explore this, thank you!

**Comment by adamrushy** [comment] 2021-10-13 11:57
@vladpre92 this also worked for me perfectly fine. But my UI is looking differently to yours, are you overriding the Appearance.Images? My feeling is that your assets aren't being bundled correctly on archive and it's defaulting to the "red circle" that we implemented.

Can you share the code whereby this is happening for some of the images? I checked your sample code but I can't see this?

**Comment by vladpre92** [comment] 2021-10-13 12:45
I tried with:

`Appearance.default.images.bigPlay = UIImage(named: "ic_video_play") ?? emptyImage`

Same result. Everything ok when running from XCode, red circles for testflight.
Also updated the above answer with my chat client configuration code.

**Comment by adamrushy** [comment] 2021-10-13 16:05
@vladpre92 are you able to send across the actual project? I can't see anything in the SDK whereby this is broken but I am thinking that something is wrong within the assets you're using/overriding.

If you can email that to me and password protect it? Then I can delete it once this issue is resolved.

Otherwise, I am struggling to reproduce this issue locally.

**Comment by vladpre92** [comment] 2021-10-13 17:39
@nuno-vieira Yes. Cocoapods.

**Comment by nuno-vieira** [comment] 2021-10-13 17:46
@vladpre92 Yes the issue seems to be related to Cocoapods. My guess is that the fix we did here for SPM: https://github.com/GetStream/stream-chat-swift/pull/1516, we also need to do it for Cocoapods. We will tackle this ASAP, and see if this fixes the issue 👍

**Comment by vankien96** [comment] 2021-10-20 04:28
@adamrushy Thank you for your work. It might not a good solution but at least you know what is the root problem. Hope you can fix that soon.

**Closed** 2021-10-20 13:45 UTC
Labels: bug
