### ISSUE TITLE
CurrentUser reports incorrect value for IsInvisible

### ISSUE THREAD

**Issue by sgoodwin** [GetStream/stream-chat-swift#2461] opened 2023-01-25 10:02 UTC
## What did you do?

1. I set a user to invisible. Verify from the app Explorer that the user is in fact invisible.
2. I use the `CurrentUserController` in the iOS app to check the `isInvisible` value and find that it reports false, even though it should report true.

## What did you expect to happen?

The `CurrentUserController`'s `CurrentUser` object should show that the user's `isInvisible` value is set to true.

## What happened instead?

It reports false.

## GetStream Environment
**GetStream Chat version:** 4.26.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** Latest
**Xcode version:** Latest
**Device:** iPhone 13Pro

**Comment by alteral** [comment] 2023-01-25 11:12
Hi @sgoodwin,

Any chance you forgot to call `synchronize()`? I think this might be the root cause.
Hope this helps!

Best,
Alex

**Comment by sgoodwin** [comment] 2023-01-25 11:28
Hi @alteral. At first I thought it was that, but even when doing that beforehand, the issue persists:

`let controller = ChatClient.shared.currentUserController()
        controller.synchronize { error in
            if let error {
                Log.stream.error("Failed to fetch current user's info.", privateMessage: error.localizedDescription)
                return
            }
            if let user = controller.currentUser {
                self.isOnline = user.isOnline
                self.isVisible = !user.isInvisible
                print("User is now visible \(self.isVisible)")
            }
        }`

Here's how we are reading the value.

**Comment by sgoodwin** [comment] 2023-01-25 13:58
We're updating it on the server-side with our Go code. We're trying to have this work as a toggle in the app for the user to control, so setting it when connecting doesn't work for us.

**Comment by alteral** [comment] 2023-01-27 12:08
Hey @sgoodwin,
This is currently not supported on the backend. 

I will let you know when we implement this feature. ETA is probably next week.
Hope it will work out of the box on iOS. Anyway, will keep you posted 👍

Best,
Alex

**Comment by sgoodwin** [comment] 2023-01-27 13:58
Ohhh ok. Thank you for the information!

**Comment by Crysis21** [comment] 2023-02-03 11:25
hey @alteral, we're currently looking to implement a toggle to set offline/online state for a user on our backend. What we need, is to hide the current user's online flag from others. Just to double check, this won't work, because is not supported on backend? So the only solution currently available is to disconnect/reconnect the user with different visibility flag? 

Thank you,
Cristian

**Comment by alteral** [comment] 2023-02-03 11:37
Hey @Crysis21, 

> the only solution currently available is to disconnect/reconnect the user with different visibility flag.

That's correct. 

The backend team is investigating the implementation of the requested feature. We'll comment here as soon as we have any updates.

Best,
Alex

**Comment by Crysis21** [comment] 2023-03-06 14:11
hey @alteral , any news on this?

**Comment by alteral** [comment] 2023-03-07 16:38
Hey @Crysis21, it's currently in the backend team's backlog. Unfortunately, it took longer than we expected and there is no ETA at the moment. But we will share updates in this ticket as soon as possible.

**Comment by shodgetts** [comment] 2023-03-27 22:27
Hi folks, could you please email me your app_id's or organization names please? It's tough for us to prioritise fixes when we don't know who you are. thanks! stephen@getstream.io

**Comment by nuno-vieira** [comment] 2023-05-15 15:19
Hello @sgoodwin, @Crysis21!

We are closing this issue here in the iOS repo for now. We recommend that you open a support ticket at support@getstream.io so that our Backend and Support team can track this more easily. 

Best,
Nuno

**Closed by nuno-vieira** 2023-05-15 15:19 UTC
Labels: 🙏 Feature Request, 🖥️ Backend
