### ISSUE TITLE
TokenProvider not triggering refresh and causing infinite API calls

### ISSUE THREAD

**Issue by oleg-rocks** [GetStream/stream-chat-swift#3145] opened 2024-04-11 19:35 UTC
## What did you do?
Passed a closure of type TokenProvider to the connectUser function. The initial connection went fine.

## What did you expect to happen?
Expected that the corresponding API call would be made when the first token was about to expire.

## What happened instead?
No API calls were made to our backend, and instead, an infinite loop of API calls to the Stream backend would start 6 min (token expiry time) after the initial connection:
https://chat.stream-io-api.com/sync?api_key=<key>
https://chat.stream-io-api.com/channels?api_key=<key>&payload=...
...
...

Proxyman app doesn't see any api calls made to our backend to refresh the token. My colleagues from Android and Web don't experience issues with token refreshment using the same user credentials. Could there be an issue in the Stream SDK's source code? If the problem is on our side, what might it be? I've found similar issue topics here, but the key difference is that I'm using the latest version of Stream, and the initial connection for the user goes fine which means that the closure should work. The problems begin only when the token needs to be refreshed.

**Logs (api key is replaced with a fake one)**
2024-04-11 23:32:00.422030+0400 name-of-the-app[16326:3030814] Task <E7C8EA08-0A08-4A2E-8590-2A65F6DD1721>.<1> finished with error [57] Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={NSErrorFailingURLStringKey=wss://chat.stream-io-api.com/connect?api_key=111111111&json=%7B%22user_id%22:%22D592A40E8A6E4E28BF8394B675E336189770B658E070C5ED4E9DB394CBBEB2B9%22,%22user_details%22:%7B%22id%22:%22D592A40E8A6E4E28BF8394B675E336189770B658E070C5ED4E9DB394CBBEB2B9%22,%22name%22:%22Rocky%20Ng%22%7D,%22server_determines_connection_id%22:true%7D, NSErrorFailingURLKey=wss://chat.stream-io-api.com/connect?api_key=111111111&json=%7B%22user_id%22:%22D592A40E8A6E4E28BF8394B675E336189770B658E070C5ED4E9DB394CBBEB2B9%22,%22user_details%22:%7B%22id%22:%22D592A40E8A6E4E28BF8394B675E336189770B658E070C5ED4E9DB394CBBEB2B9%22,%22name%22:%22UserName%20Ng%22%7D,%22server_determines_connection_id%22:true%7D, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalWebSocketTask <E7C8EA08-0A08-4A2E-8590-2A65F6DD1721>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalWebSocketTask <E7C8EA08-0A08-4A2E-8590-2A65F6DD1721>.<1>}

## GetStream Environment
**GetStream Chat version:** 4.52.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.4
**Swift version:** 5.8.1.
**Xcode version:** 14.3.1
**Device:** iPhone 14 Pro

## Additional context

Attaching the code of the classes responsible for chat user connection.

```
final class Chat {
    static var shared = Chat()

    private(set) var client: ChatClient

    private init() {
        let config = ConfigLoader.parseFile()
        let apiKey = Chat.selectApiKey(using: config)
        let chatConfig = ChatClientConfig(apiKey: APIKey(apiKey))
        client = ChatClient(config: chatConfig)
    }

    private static func selectApiKey(using config: Configuration) -> String {
        let persistenceStorage = PersistenceStorage()
        let currentProdRegionConfig: RegionConfiguration? = try? persistenceStorage.getValue(
            storageType: .userDefaults,
            key: Constants.UserDefaults.currentProductionRegionConfiguration
        )

        if let regionConfig = currentProdRegionConfig,
           regionConfig.apiUrl == AppRegion.regionTwo.url {
            return config.streamChatApiKeyRegionTwo ?? config.streamChatApiKeyRegionOne
        } else {
            return config.streamChatApiKeyRegionOne
        }
    }
}

class ChatManager: ChatManagerProtocol {
    private let persistenceStorage: PersistenceStorageProtocol
    private var streamChat: StreamChat?
    private let authRepository: AuthRepositoryProtocol
    private let disposeBag = DisposeBag()
    private(set) var unreadChatMessages = BehaviorRelay<Int>(value: 0)
    private(set) var chatNotificationInfo = BehaviorRelay<ChatNotificationInfo?>(value: nil)

    private var profile: ProfileResponse? {
        try? persistenceStorage.getValue(
            storageType: .userDefaults,
            key: Constants.UserDefaults.profile
        )
    }

    var hasViewedChatBetaMessage: Bool {
      ...
    }

    var connectionStatus: BehaviorRelay<ChatConnectionStatus> = BehaviorRelay(value: .disconnected)

    init(
        persistenceStorage: PersistenceStorageProtocol,
        authRepository: AuthRepositoryProtocol
    ) {
        self.persistenceStorage = persistenceStorage
        self.authRepository = authRepository
    }

    func updateChatNotificationInfo(_ notificationInfo: ChatNotificationInfo) {
        chatNotificationInfo.accept(notificationInfo)
    }

    func clearChatNotificationInfo() {
        chatNotificationInfo.accept(nil)
    }

    func connectUser() -> Completable {
        Completable.create { [unowned self] complete in
            if connectionStatus.value == .connected {
                complete(.completed)
            }

            if streamChat == nil {
                streamChat = StreamChat(chatClient: Chat.shared.client)
            }

            var avatar: URL? = nil

            if let string = profile?.avatar, let url = URL(string: string) {
                avatar = url
            }

            if let id = profile?.chatUserId {
                connectionStatus.accept(.connecting)

                let userInfo = UserInfo(
                    id: id,
                    name: profile?.name,
                    imageURL: avatar
                )

                connect(
                    userInfo: userInfo,
                    onSuccess: {
                        complete(.completed)
                    },
                    onError: { error in
                        complete(.error(AppErrors(error: error)))
                    }
                )
            } else {
                self.connectionStatus.accept(.disconnected)
                complete(.error(AppErrors.generic))
            }

            return Disposables.create()
        }
        .observeOn(MainScheduler.instance)
    }

    func loadToken(completion: @escaping (Result<Token, Error>) -> Void) {
        authRepository.chatToken()
            .subscribe(
                onSuccess: { response in
                    if let chatToken = response.chatToken {
                        do {
                            let token = try Token(rawValue: chatToken)
                            completion(.success(token))
                        } catch {
                            completion(.failure(AppErrors.generic))
                        }
                    } else {
                        completion(.failure(AppErrors.generic))
                    }
                },
                onError: { error in
                    completion(.failure(error))
                }
            )
            .disposed(by: disposeBag)
    }

    func subscribeToUnreadChatMessages() {
        Observable<Int>.create { observer in
            let subscription = Chat.shared.client.currentUserController()
                .unreadCountPublisher
                .sink(
                    receiveCompletion: { _ in },
                    receiveValue: { unreadCount in
                        observer.onNext(unreadCount.messages)
                    }
                )
            return Disposables.create {
                subscription.cancel()
            }
        }
        .catchErrorJustReturn(0)
        .bind(to: unreadChatMessages)
        .disposed(by: disposeBag)
    }

    func disconnectUser(completion: (() -> Void)? = nil) {
        connectionStatus.accept(.disconnecting)

        Chat.shared.client.disconnect { [weak self] in
            self?.unregisterDeviceFromPushNotifications()
            self?.connectionStatus.accept(.disconnected)
            completion?()
        }
    }

    func logout(completion: (() -> Void)?) {
        connectionStatus.accept(.disconnecting)

        Chat.shared.client.logout { [weak self] in
            self?.unregisterDeviceFromPushNotifications()
            self?.connectionStatus.accept(.disconnected)
            completion?()
        }
    }

    func markChatBetaMessageAsViewed() {
        ...
    }

    private func connect(
        userInfo: UserInfo,
        onSuccess: @escaping () -> Void,
        onError: @escaping (Error) -> Void
    ) {
        Chat.shared.client.connectUser(
            userInfo: userInfo,
            tokenProvider: loadToken
        ) { [weak self] error in
            if let error = error {
                self?.connectionStatus.accept(.disconnected)
                onError(error)
            } else {
                self?.registerDeviceToPushNotifications()
                self?.connectionStatus.accept(.connected)
                onSuccess()
            }
        }
    }
}
```

**Comment by testableapple** [comment] 2024-04-12 14:22
Hi @oleg-rocks,
Thanks for opening the issue.

Let me ask you a couple of questions:
- In this code, `loadToken` is a function, but it seems like the code example was edited. Is everything correct there?
```swift
Chat.shared.client.connectUser(
        userInfo: userInfo,
        tokenProvider: loadToken
)
```
- Could you show us how do you create `authRepository`? Curious about `tokenExpirationRetryStrategy` in particular.
- We fixed this issue in [4.50.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.50.0), could you try that version just to double-check?

Best,
Alexey

**Comment by testableapple** [comment] 2024-04-12 14:37
@oleg-rocks, also, if nothing helps, you might want to try reproducing this issue in our [DemoApp](https://github.com/GetStream/stream-chat-swift/tree/develop/DemoApp) (with your own `app secret`) following the `Manual Testing Notes` from [the PR](https://github.com/GetStream/stream-chat-swift/pull/3052) where we fixed this issue.
Eventually, you could try to align your source code accordingly using the code examples from our DemoApp.

Hope this helps!

Best,
Alexey

**Comment by oleg-rocks** [comment] 2024-04-12 15:29
> Hi @oleg-rocks, Thanks for opening the issue.
> 
> Let me ask you a couple of questions:
> 
> * Could you show us how do you create `authRepository`? Curious about `tokenExpirationRetryStrategy` in particular.
> * We fixed this issue in [4.50.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.50.0), could you try that version just to double-check?
> 
> Best, Alexey

```
class AuthRepository {
    private let api = MoyaProvider<AuthApi>()
}

extension AuthRepository: AuthRepositoryProtocol {
    func login(request: LoginRequest) -> Single<LoginResponse> {
        api.rx
            .request(.login(request: request))
            .map(LoginResponse.self)
    }

...

    func chatToken() -> Single<ChatTokenResponse> {
        api.rx
            .request(.chatToken)
            .map(ChatTokenResponse.self)
    }
}

enum AuthApi {
...
    case chatToken
}

extension AuthApi: TargetType {
    public var baseURL: URL { environmentBaseURL }

    public var path: String {
        switch self {
       ....
        case .chatToken:
            return "/user/chattoken"
        }
    }

    public var method: Moya.Method {
        switch self {
         ...
        case ..chatToken:
            return .get
        }
    }

    public var task: Task {
        switch self {
    ...
        case .chatToken:
            return .requestPlain
    ...
    }

    public var sampleData: Data {
        switch self {
        case .login:
            return try! JSONEncoder().encode(LoginResponse.mock())
        default:
            return Data()
        }
    }

    public var headers: [String: String]? {
        nil
    }

    public var validationType: ValidationType {
        .successCodes
    }
}

extension AuthApi: EndpointRepresentable {
    var endpointStatusCode: Int {
        200
    }

    var stubBehavior: StubBehavior {
        .delayed(seconds: 1)
    }
}

```

**Comment by testableapple** [comment] 2024-04-15 09:06
Hi @oleg-rocks,

Thanks for sharing the code. Unfortunately, it did not help to find the root cause of your issue.

Have you had a chance to check [4.50.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.50.0) or reproduce the issue in our DemoApp (and try to replace your source code with the code from our DemoApp if it works)?

Best,
Alexey

**Comment by testableapple** [comment] 2024-04-18 09:24
Hi @oleg-rocks,

I'm closing this ticket since this issue was fixed a couple of releases ago and we can't reproduce it on our side at the moment. If you still face this issue, feel free to report this to [support@getstream.io](mailto:support@getstream.io), mentioning this closed GitHub issue. Our support team will be able to identify if this is an issue on our side.

Best wishes,
Alexey

**Closed by testableapple** 2024-04-18 09:24 UTC
Labels: ❓ Question
