### ISSUE TITLE
Users imageURL in the wrong place

### ISSUE THREAD

**Issue by j-j-m** [GetStream/stream-chat-swift#1479] opened 2021-09-26 20:32 UTC
## What did you do?
Connected a user with `ChatClient.connectUser` including an imageURL in the user info i.e.
```
liveChatClient.connectUser(
                    userInfo: .init(
                        id: <id>,
                        name: <username>,
                        imageURL: <image url>,
                        extraData: [:]),
                    token: Token(stringLiteral: <token string>)
                )
```

## What did you expect to happen?
When accessing the user via `channel.lastActiveMembers` or `channel.lastActiveWatchers` 
`ChatUser.imageURL` should contain the users image URL

## What happened instead?
`ChatUser.imageURL` was nil. `ChatUser.extraData["image_url"]` instead contained the url. This seems wrong and is sort of cumbersome.

## GetStream Environment
**GetStream Chat version:**
4.0.2
**GetStream Chat frameworks:** 
StreamChat
**iOS version:**
15
**Swift version:**
5.5
**Xcode version:**
13
**Device:**
All

**Comment by adamrushy** [comment] 2021-09-27 08:33
Hi @j-j-m thanks for reporting this. This is intended behaviour and the SDK is built to do this. 

I have just run the Demo app and I can see that `lastActiveMembers` does return `imageURL`. If possible, can you provide some more code snippets so I can see the actual integration?

It's worth noting that `imageURL` is optional and will default to `nil` so I am wondering if you're setting a valid URL type. But let me know more information and I will help you further.

**Comment by adamrushy** [comment] 2021-09-27 10:07
@j-j-m To update we have found the issue and will feedback with a fix shortly thank you.

**Comment by adamrushy** [comment] 2021-09-27 16:13
@j-j-m this issue will be fixed with this PR https://github.com/GetStream/stream-chat-swift/pull/1482

Thank you for reporting :)

**Comment by tbarbugli** [comment] 2021-09-28 07:16
the PR is merged and will be part the next release (before end of the week). If you have the chance please test against main and let us know if you still see any issue

**Closed** 2021-09-28 19:02 UTC
Labels: bug
