### ISSUE TITLE
"MemberRole string value `user` doesn\'t match any of the known roles", underlyingError: nil))

### ISSUE THREAD

**Issue by BarragaoA** [GetStream/stream-chat-swift#1279] opened 2021-07-15 09:09 UTC
Hello

## What did you do?
I'm fetching channel list :

> let query = ChannelListQuery(filter: Filter.containMembers(userIds: [userId]), sort: [Sorting(key: .lastMessageAt)], pageSize: .max, messagesLimit: .max)
>         let channelList = ChatClient.shared.channelListController(query: query)
>         channelList.synchronize { error in
>             if error != nil {
>                 completion(.failure(error!))
>             } else{
>                 let unreadChannels = channelList.channels.filter { channel in
>                     channel.isUnread
>                 }
>                 completion(.success(unreadChannels))
>             }
>         }

## What did you expect to happen?
Get channel list

## What happened instead?
Everything was working well on tuesday but since this morning I got the following error :
`[ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:71] [decodeRequestResponse(data:response:error:)] > dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "channels", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "membership", intValue: nil), CodingKeys(stringValue: "role", intValue: nil)], debugDescription: "MemberRole string value `user` doesn\'t match any of the known roles", underlyingError: nil))`
Did something change ?

## GetStream Environment
**GetStream Chat version:** 3.1.11
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 14.4.2
**Swift version:** 5
**Xcode version:** 12.5.1
**Device:** iPhone Xr

## Additional context
Thanks for your help

**Comment by BarragaoA** [comment] 2021-07-15 10:01
Actually I understand that I'm receiving a bad memberRole value. Why do I receive 'user' as MemberRole value ?

**Comment by whiplash00** [comment] 2021-07-15 16:23
I suddenly got this same issue since early this week. This bug seems to stop new channels from showing up in the directory (using development token). I have to make everyone admin role in order for things to continue to work. Please fix it asap.

**Comment by tbarbugli** [comment] 2021-07-16 08:36
@BarragaoA @whiplash00 there was an API regression that returned "user" instead of "member" for the membership role. These two are aliases but unfortunately the iOS SDK is rather strict about this. A patch for this was rolled out yesterday and does not require updating anything on the SDK. 

I am going to close this one, please re-open if you can still reproduce this issue.

**Closed by tbarbugli** 2021-07-16 08:36 UTC
Labels: bug
