### ISSUE TITLE
Channel list filter logic broken

### ISSUE THREAD

**Issue by Subtextaps** [GetStream/stream-chat-swift#2556] opened 2023-04-02 11:43 UTC
## What did you do?

When updating the SDK from 4.27.0 to 4.30.0 the channel list filter logic seems to break.

## What did you expect to happen?

With 4.27.0 the following piece of code would show a channel list containing all "public" livestream channels (meaning channels that any user can watch without being a member) as well as all channels of which the user is a member. 

   if let chatID = self.userStatusHandler.userStatus.chatID {
                
                let filter = Filter<ChannelListFilterScope>
                    .or(
                        [.equal(.type, to: .livestream),
                         .containMembers(userIds: [chatID])
                    ]
                    )
            
            self.channelListController = self.chatClient.channelListController(
                query: .init(filter:
                        filter)
                )
            
            self.channelListController?.synchronize ({ [weak self] error in
                if let error = error {
                    print(error.localizedDescription)
                    self?.alertContent = AlertContent(title: "Fejl", message: "Noget gik galt. Prøv at lukke appen helt og åbne igen", dismissButtonText: "Ok")
                    self?.showAlert = true
                    return
                }
                else {
                    
                    
                    DispatchQueue.main.async {
                    self?.channelListViewModel = ViewModelsFactory.makeChannelListViewModel(
                        channelListController: self?.channelListController)
                    
                  
                        self?.chatService.currentAlert = .none
                        self?.showAlert = false
                        self?.showChatIntro = false
                        self?.showChannels = true
                        
                    }
                }
            })
        }

## What happened instead?

After updating only channels of which the user is a member are shown. The livestream channels of which the user is not a member are no longer shown. Sometimes the list does show all the channels in the query briefly, right after the channel list appears. But they are removed after a second or so.

## GetStream Environment
**GetStream Chat version:**
4.30.0
**GetStream Chat frameworks:** 
StreamChat, StreamChatSwiftUI
**iOS version:**
16.3.1
**Swift version:**
5.0
**Xcode version:**
14.3
**Device:**
iPhone 11

**Comment by nuno-vieira** [comment] 2023-04-03 17:41
Hi @Subtextaps!

Thank you for your report! We were able to reproduce the issue and identify the root cause 👍 

We will let you know once we have a fix. 

In the meantime, your workaround will be fine, but your filter will work automatically without providing a filter block once we provide the fix. 

Best,
Nuno

**Comment by nuno-vieira** [comment] 2023-04-04 09:51
Hi @Subtextaps!

The fix is already on `develop` and it will be available in the next release 👍 

Best,
Nuno

**Comment by Subtextaps** [comment] 2023-04-04 12:28
Great to hear – thanks for your help with this🙏🏼

Best,

Thomas

**Comment by polqf** [comment] 2023-04-26 08:37
Hi @Subtextaps, 
[4.31.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.31.0) is out, and contains the fix for this issue.

Let us know if you need anything else from us

**Closed** 2023-04-26 08:37 UTC
Labels: 🐞 Bug, 🌐 SDK: StreamChat (LLC), 🔜 Upcoming
