### ISSUE TITLE
Deleted chat doesn't remove from channelList

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#1818] opened 2022-03-01 12:33 UTC
## What did you do?
1. Create a channel with multiple users.
2. Newly created channel displayed in the channel list for all channel members.
3. Admin user deletes the channel with `channelController.deleteChannel()`

## What did you expect to happen?
- Deleted channel should remove from channelList for all channel members.

## What happened instead?
- Deleted channel still remain in the user's channel List.

## GetStream Environment
**GetStream Chat version:** 4.10.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.0.2
**Swift version:** 5.2
**Xcode version:** 13.2
**Device:** Iphone X

**Comment by b-onc** [comment] 2022-03-01 14:19
Hello @ajay-simform ,

Can you share the query you're using for displaying Channel List?

**Comment by ajay-simform** [comment] 2022-03-02 05:40
@b-onc  query for displaying channel list.

```
let controller = ChatClient.shared.channelListController(
            query: .init(filter: .containMembers(userIds: [ChatClient.shared.currentUserId!])))
```

When isLocalStorageEnabled = false, deleted channel remove from the list when restarting the app.
But it stays there when isLocalStorageEnabled = true

**Comment by b-onc** [comment] 2022-03-03 13:42
Hello @ajay-simform ,

I cannot reproduce this issue with our DemoApp. Whenever a channel is deleted, it's correctly removed from the channel list. Can you provide a sample app where this issue is reproducible?

**Comment by nuno-vieira** [comment] 2022-03-09 16:55
Hi @ajay-simform!

Are you sure you are using the 4.10.1 version?
Because this should be fixed in that version. And we can't reproduce this on our DemoApp currently. 

Best,
Nuno

**Closed as completed** 2022-03-15 15:11 UTC
