### ISSUE TITLE
Crash With a Fatal Exception: NSInternalInconsistencyException, Invalid Batch Updates Detected

### ISSUE THREAD

**Issue by edanilaydagdemir** [GetStream/stream-chat-swift#2848] opened 2023-10-25 13:02 UTC
## What did you do?

1. Presented a ChatViewController
2. User sent 3 messages
3. Move to different screens
4. App crashes

## What did you expect to happen?

ChatViewController to work correctly without a crash.

## What happened instead?

A crash.

## GetStream Environment
**GetStream Chat version:** 4.32.0
**GetStream Chat frameworks:** StreamChat
**iOS version:** 16.7.1 (from user crash logs)
**Swift version:**Swift 5
**Xcode version:**14.3.1
**Device:**iPhone 14 Pro Max (from user crash logs)

## Additional context

**Exception Info:**

Fatal Exception: NSInternalInconsistencyException
Invalid batch updates detected: the number of sections and/or items returned by the data source before and/or after performing the batch updates are inconsistent with the updates. Data source before updates = { 1 section with item counts: [21] } Data source after updates = { 1 section with item counts: [20] } Updates = [ Delete item (0 - 12), Delete item (0 - 11), Delete item (0 - 10), Delete item (0 - 9), Delete item (0 - 8), Delete item (0 - 7), Delete item (0 - 6), Delete item (0 - 5), Delete item (0 - 4), Delete item (0 - 3), Delete item (0 - 2), Delete item (0 - 1), Delete item (0 - 0), Insert item (0 - 0), Insert item (0 - 1), Insert item (0 - 2), Insert item (0 - 3), Insert item (0 - 4), Insert item (0 - 5), Insert item (0 - 6), Insert item (0 - 7), Insert item (0 - 8), Insert item (0 - 9), Insert item (0 - 10), Insert item (0 - 11), Insert item (0 - 12) ] Collection view: <UICollectionView: 0x10baec400; frame = (0 0; 430 932); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x283111e60>; backgroundColor = <UIDynamicProviderColor: 0x283fca6a0; provider = <__NSMallocBlock__: 0x2831cba80>>; layer = <CALayer: 0x283f284e0>; contentOffset: {0, -149.66666666666666}; contentSize: {430, 1350.6666666666667}; adjustedContentInset: {149.66666666666666, 0, 34, 0}; layout: <StreamChatUI.ListCollectionViewLayout: 0x121cf8b00>; dataSource: <{OURAPPNAME}.ChannelListViewController: 0x10c073200>>

Stack trace from a crash:
# Stack trace

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation            0x9c44 (Missing UUID df935525036c30ae8d1d4e5f3dd7876a)
1  libobjc.A.dylib                0x17e5c (Missing UUID 1ff34faad6c3319bb651854379e9eadf)
2  Foundation                    0x4e150c (Missing UUID 08587e68599130bba36237b31c21007e)
3  UIKitCore                       0x7023dc (Missing UUID 875d830b862c39928c803aa14044915d)
4  UIKitCore                       0x30d024 (Missing UUID 875d830b862c39928c803aa14044915d)
5  UIKitCore                       0x26b41c (Missing UUID 875d830b862c39928c803aa14044915d)
6  {OURAPPNAME}          0xccc12c @nonobjc UICollectionView.performBatchUpdates(_:completion:)
7  {OURAPPNAME}          0xccc8e8 specialized ListChangeUpdater.performUpdate<A>(on:with:pathResolver:completion:) + 45 (ListChangeUpdater.swift:45)
8  {OURAPPNAME}          0xcca850 CollectionViewListChangeUpdater.performUpdate<A>(with:completion:) + 24 (CollectionViewListChangeUpdater.swift:24)
9  {OURAPPNAME}          0xcca8c4 protocol witness for ListChangeUpdater.performUpdate<A>(with:completion:) in conformance CollectionViewListChangeUpdater (<compiler-generated>)
10 {OURAPPNAME}        0xb455ac ChatChannelListVC.controller(_:didChangeChannels:) + 378 (ChatChannelListVC.swift:378)
11 {OURAPPNAME}        0x95ff80 ChannelListViewController.controller(_:didChangeChannels:) + 86 (ChannelListViewController.swift:86)
12 {OURAPPNAME}       0xd97dec closure # 1 in closure # 2 in closure # 1 in ChatChannelListController.channelListObserver.getter
13 {OURAPPNAME}        0xd5df24 specialized MulticastDelegate.invoke(_:)
14 {OURAPPNAME}        0xdc0938 specialized DelegateCallable.delegateCallback(_:) + 95 (DataController.swift:95)
15 {OURAPPNAME}        0xd97bb0 closure # 2 in closure # 1 in ChatChannelListController.channelListObserver.getter
16 {OURAPPNAME}        0xf4da98 specialized closure # 1 in ListDatabaseObserver.onChange.didset
17 {OURAPPNAME}        0xdb5830 specialized ListChangeAggregator.controllerDidChangeContent(_:) + 417 (ListDatabaseObserver.swift:417)
18 {OURAPPNAME}        0xdb4784 @objc ListChangeAggregator.controllerDidChangeContent(_:) (<compiler-generated>)

**Comment by nuno-vieira** [comment] 2023-10-26 12:59
Hi @edanilaydagdemir!

This crash should be fixed by the latest SDK updates. A diffing solution for the Channel List was introduced after 4.35+. Please update the SDK to the latest 4.40.0 and see if the issue is still reproducible. If it is, feel free to re-open this issue.

Best,
Nuno

**Closed by nuno-vieira** 2023-10-26 12:59 UTC
